//! Solidity verifier contract emission for Halo2 ZK circuits.
//!
//! Generates a minimal Solidity contract skeleton that will eventually contain
//! the on-chain Halo2/KZG pairing check. In v1 the contract is a structural
//! placeholder with the correct interface — the actual BN254 pairing verification
//! (using `ecPairing` precompile at address 0x08) requires the full KZG verifying
//! key, which is produced by a follow-up task.
//!
//! ## Usage
//!
//! ```rust,ignore
//! let sol = emit_solidity_verifier("MyModel", &vk_hash);
//! std::fs::write("MyModelVerifier.sol", sol).unwrap();
//! ```

/// Emit a Solidity verifier contract for the given circuit name and VK hash.
///
/// # Arguments
/// - `circuit_name`: human-readable model/circuit name (used in the contract name).
/// - `vk_hash`: 32-byte hash of the verification key, embedded as a constant.
///
/// # Returns
/// A complete Solidity source file as a `String`.
pub fn emit_solidity_verifier(circuit_name: &str, vk_hash: &[u8; 32]) -> String {
    let vk_hex = bytes_to_hex(vk_hash);

    format!(
        r#"// SPDX-License-Identifier: MIT
// Auto-generated by NSL ZK compiler (M55)
pragma solidity ^0.8.0;

contract {name}Verifier {{
    bytes32 constant VK_HASH = 0x{vk_hex};

    function verify(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external pure returns (bool) {{
        // Halo2 KZG pairing check placeholder
        // Full implementation requires on-chain pairing precompiles (ecPairing at 0x08)
        require(proof.length > 0, "Empty proof");
        require(publicInputs.length > 0, "No public inputs");
        // VK_HASH check would go here
        return true; // Placeholder -- real verification uses bn256 pairing
    }}
}}
"#,
        name = circuit_name,
        vk_hex = vk_hex
    )
}

/// Convert a byte slice to a lowercase hex string (no `0x` prefix).
fn bytes_to_hex(bytes: &[u8]) -> String {
    let mut hex = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        hex.push_str(&format!("{b:02x}"));
    }
    hex
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn solidity_emitter_produces_contract() {
        let sol = emit_solidity_verifier("TestModel", &[0u8; 32]);
        assert!(
            sol.contains("contract TestModelVerifier"),
            "contract name must include circuit name"
        );
        assert!(
            sol.contains("function verify"),
            "must contain verify function"
        );
        assert!(
            sol.contains("pragma solidity"),
            "must contain pragma"
        );
    }

    #[test]
    fn solidity_emitter_embeds_vk_hash() {
        let mut vk = [0u8; 32];
        vk[0] = 0xAB;
        vk[31] = 0xCD;
        let sol = emit_solidity_verifier("Hash", &vk);
        // vk_hash should contain the hex encoding.
        assert!(
            sol.contains("ab"),
            "VK_HASH must contain hex of first byte"
        );
        assert!(
            sol.contains("cd"),
            "VK_HASH must contain hex of last byte"
        );
    }

    #[test]
    fn solidity_emitter_spdx_license() {
        let sol = emit_solidity_verifier("License", &[0u8; 32]);
        assert!(
            sol.contains("SPDX-License-Identifier: MIT"),
            "must contain SPDX license"
        );
    }

    #[test]
    fn solidity_emitter_nsl_attribution() {
        let sol = emit_solidity_verifier("Attr", &[0u8; 32]);
        assert!(
            sol.contains("NSL ZK compiler"),
            "must contain NSL attribution"
        );
    }

    #[test]
    fn solidity_emitter_different_names() {
        let sol1 = emit_solidity_verifier("Alpha", &[0u8; 32]);
        let sol2 = emit_solidity_verifier("Beta", &[0u8; 32]);
        assert!(sol1.contains("contract AlphaVerifier"));
        assert!(sol2.contains("contract BetaVerifier"));
    }

    #[test]
    fn bytes_to_hex_basic() {
        assert_eq!(bytes_to_hex(&[0x00]), "00");
        assert_eq!(bytes_to_hex(&[0xff]), "ff");
        assert_eq!(bytes_to_hex(&[0xab, 0xcd]), "abcd");
        assert_eq!(bytes_to_hex(&[]), "");
    }

    #[test]
    fn solidity_vk_hash_is_64_hex_chars() {
        let sol = emit_solidity_verifier("Len", &[0u8; 32]);
        // Find "0x" followed by 64 hex chars.
        let idx = sol.find("0x").expect("must contain 0x prefix");
        let hex_part = &sol[idx + 2..idx + 2 + 64];
        assert!(
            hex_part.chars().all(|c| c.is_ascii_hexdigit()),
            "VK_HASH hex must be 64 hex digits"
        );
    }
}
