// Verilator C++ testbench for v1 MLP sequential FSM per M57.2 spec.
//
// Protocol:
//   - Reads 784 input bytes from stdin (the i8 activation vector).
//   - Async active-low reset: de-asserts rst_n for one clock edge, then
//     re-asserts it.
//   - Asserts start for one clock cycle so the FSM latches x into x_buf in
//     S_IDLE and transitions to the first MAC phase, then deasserts start.
//   - Ticks the clock until dut->done is high, counting cycles.
//   - Prints "out=0x<hex>" (MSB-first, big-endian hex) followed by
//     "measured_cycles=<n>" on its own line.
//
// NOTE: The sequential module is tiny_mlp_seq (not tiny_mlp), generated by
// KirToHirPass { sequential: true }.  Verilator generates Vtiny_mlp_seq.h.
//
// Port widths (from the emitted Verilog snapshot):
//   clk   : 1-bit input
//   rst_n : 1-bit input  (active-low async reset)
//   start : 1-bit input
//   x     : [6271:0] input  (784 × i8 = 6272 bits, 196 uint32_t words)
//   done  : 1-bit output
//   valid : 1-bit output
//   out   : [639:0] output  (10 × i64 = 640 bits, 20 uint32_t words)
//
// Bit packing: x[k*8 +: 8] == input[k], mirroring the emitted Verilog
// x_buf[k] <= x[k*8 +: 8] assignment.  Same byte-major order as testbench.cpp.
//
// Safety bound: MAX_CYCLES = 200000 (well above the deterministic 101634 + 2
// overhead cycles documented in the snapshot comment).

#include <iostream>
#include <iomanip>
#include <vector>
#include <cstdint>
#include <cstring>
#include <verilated.h>
#include "Vtiny_mlp_seq.h"

constexpr long MAX_CYCLES = 200000;

// Toggle one full clock cycle: posedge then negedge.
static inline void tick(Vtiny_mlp_seq* dut) {
    dut->clk = 1;
    dut->eval();
    dut->clk = 0;
    dut->eval();
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vtiny_mlp_seq* dut = new Vtiny_mlp_seq;

    // -----------------------------------------------------------------------
    // Read 784 i8 input values from stdin
    // -----------------------------------------------------------------------
    std::vector<int8_t> input(784);
    if (!std::cin.read(reinterpret_cast<char*>(input.data()), 784)) {
        std::cerr << "testbench_seq: failed to read 784 input bytes\n";
        return 1;
    }

    // -----------------------------------------------------------------------
    // Pack input into wide port.
    // Verilator lays out a 6272-bit port as dut->x[k] where each element
    // is a uint32_t (Verilator VL_SIZEBITS=32 default) holding 4 packed i8
    // values.  Layout: x[0] holds input[0..3], x[1] holds input[4..7], ...
    // This is identical to testbench.cpp's x_l1 packing.
    // -----------------------------------------------------------------------
    constexpr int X_WORDS = (784 + 3) / 4;  // 196 uint32_t words
    for (int i = 0; i < X_WORDS; i++) {
        uint32_t slot = 0;
        for (int b = 0; b < 4; b++) {
            int idx = i * 4 + b;
            if (idx < 784) {
                slot |= static_cast<uint32_t>(static_cast<uint8_t>(input[idx])) << (b * 8);
            }
        }
        dut->x[i] = slot;
    }

    // -----------------------------------------------------------------------
    // Async active-low reset sequence:
    //   1. Drive rst_n=0, start=0, clk=0, eval (combinational settle).
    //   2. Toggle one clock edge while rst_n=0.
    //   3. De-assert reset: rst_n=1, eval.
    // -----------------------------------------------------------------------
    dut->rst_n = 0;
    dut->start = 0;
    dut->clk   = 0;
    dut->eval();
    tick(dut);   // one cycle under reset
    dut->rst_n = 1;
    dut->eval();

    // -----------------------------------------------------------------------
    // Assert start for one clock cycle.
    // The FSM is now in S_IDLE; asserting start causes it to latch x into
    // x_buf on the next posedge and transition to the first MAC phase.
    // -----------------------------------------------------------------------
    dut->start = 1;
    tick(dut);     // posedge latches x_buf, FSM leaves IDLE
    dut->start = 0;

    // -----------------------------------------------------------------------
    // Tick until done is high, with a safety cycle limit.
    // -----------------------------------------------------------------------
    long measured_cycles = 0;
    while (!dut->done) {
        if (measured_cycles >= MAX_CYCLES) {
            std::cerr << "testbench_seq: MAX_CYCLES (" << MAX_CYCLES
                      << ") exceeded without done assertion\n";
            dut->final();
            delete dut;
            return 3;
        }
        tick(dut);
        measured_cycles++;
    }

    // -----------------------------------------------------------------------
    // Dump output port: "out=0x<hex>\n" (MSB-first, same helper as testbench.cpp).
    // out is [639:0] = 640 bits = 20 uint32_t words.
    // -----------------------------------------------------------------------
    constexpr int OUT_WORDS = 20;  // 640 / 32
    auto dump32 = [](const char* name, const uint32_t* port, int n_words) {
        std::cout << name << "=0x";
        for (int i = n_words - 1; i >= 0; i--) {
            std::cout << std::hex << std::setw(8) << std::setfill('0') << port[i];
        }
        std::cout << std::dec << "\n";
    };

    dump32("out", dut->out, OUT_WORDS);

    // -----------------------------------------------------------------------
    // Print cycle count for the Rust harness to parse.
    // -----------------------------------------------------------------------
    std::cout << "measured_cycles=" << measured_cycles << "\n";

    dut->final();
    delete dut;
    return 0;
}
