"""ctypes signatures of the NSL runtime C API.

GENERATED by `nsl abi python` from crates/nsl-abi/src/capi.rs. Do not
edit by hand: `cargo test -p nsl-abi` fails if this file and the table
differ. Every slot is an integer-sized value or a pointer passed as one
(the runtime's C API takes addresses as int64_t), so the mirror never
needs a ctypes pointer type.
"""

import ctypes

SIGNATURES = {
    "nsl_abi_version": ([], ctypes.c_int64),
    "nsl_get_last_error": ([], ctypes.c_int64),
    "nsl_clear_error": ([], ctypes.c_int64),
    "nsl_model_create": ([ctypes.c_int64], ctypes.c_int64),
    "nsl_model_create_with_lib": ([ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_destroy": ([ctypes.c_int64], ctypes.c_int64),
    "nsl_model_get_version": ([], ctypes.c_int64),
    "nsl_model_num_weights": ([ctypes.c_int64], ctypes.c_int64),
    "nsl_model_export_count": ([ctypes.c_int64], ctypes.c_int64),
    "nsl_model_lookup_function": ([ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_call": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_call_into": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_call_alloc": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_call_dlpack": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_get_export_signature": ([ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_forward_dlpack": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_dlpack_export": ([ctypes.c_int64], ctypes.c_int64),
    "nsl_dlpack_import": ([ctypes.c_int64], ctypes.c_int64),
    "nsl_dlpack_free": ([ctypes.c_int64], None),
    "nsl_model_forward_grad": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_model_backward": ([ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_int64], ctypes.c_int64),
    "nsl_grad_context_destroy": ([ctypes.c_int64], None),
}


def bind(lib, names=None):
    """Set argtypes/restype on `lib` for the table symbols it exports.

    `names` restricts the binding to a subset; a symbol absent from `lib`
    is skipped, so one call serves both the standalone runtime and an
    @export shared library that statically links it (which may predate
    some of the entry points).
    """
    for name in SIGNATURES if names is None else names:
        if hasattr(lib, name):
            fn = getattr(lib, name)
            fn.argtypes, fn.restype = SIGNATURES[name]
