//! `nsl doc cli` — the CLI reference page, rendered from the clap command
//! tree (roadmap Doc2).
//!
//! `docs/wiki/CLI-Reference.md` is generated by this module and gated by
//! `wiki_page_is_the_command_tree_rendering` below, the same arrangement as
//! `docs/wiki/Environment-Variables.md` and `nsl env list --markdown`: the
//! page cannot drift from `args.rs` because `cargo test -p nsl-cli` compares
//! the two. Every subcommand, positional and flag that `nsl <cmd> --help`
//! shows is on the page, in the same words; nothing is written by hand.

use std::fmt::Write as _;

use clap::{Arg, ArgAction, Command};

/// Render the whole reference page for `cmd` (the built `nsl` command).
pub(crate) fn render_markdown(root: &Command) -> String {
    let mut root = root.clone();
    // `build()` resolves the derived defaults (help/version args, bin names
    // of nested subcommands) so `render_usage` prints `nsl build …` and not
    // `build …`.
    root.build();
    let mut out = String::new();
    let visible = collect(&root);
    let _ = writeln!(out, "# CLI reference");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "<!-- GENERATED by `nsl doc cli` from crates/nsl-cli/src/args.rs. Do not edit by hand: \
         `cargo test -p nsl-cli` fails if this page and the command tree differ. -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Every `nsl` subcommand ({} of them), with each one's positionals and flags in the words \
         of `nsl <command> --help` (this page and the help text are rendered from the same \
         declarations). Flags are listed with the value they take (a flag with no value is a \
         switch; `(optional)` means the flag may be given bare), the default that applies when \
         the flag is absent, and — for an enumerated flag — the accepted values. `nsl --version` \
         prints the toolchain version; `nsl <command> --help` prints one command's page.",
        visible.len().saturating_sub(1)
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Commands");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Command | Purpose |");
    let _ = writeln!(out, "|---|---|");
    for cmd in visible.iter().skip(1) {
        let path = bin_name(cmd);
        let _ = writeln!(out, "| [`{}`](#{}) | {} |", path, anchor(&path), cell(&about(cmd)));
    }
    let _ = writeln!(out);
    for (i, cmd) in visible.iter().enumerate() {
        render_command(&mut out, cmd, i == 0);
    }
    // One trailing newline, not a blank line: an editor that trims final
    // newlines would otherwise fail the gate on a page nobody edited.
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

/// The root and every visible subcommand, depth-first in declaration order.
fn collect(root: &Command) -> Vec<&Command> {
    fn walk<'a>(cmd: &'a Command, into: &mut Vec<&'a Command>) {
        into.push(cmd);
        for sub in cmd.get_subcommands() {
            if sub.is_hide_set() || sub.get_name() == "help" {
                continue;
            }
            walk(sub, into);
        }
    }
    let mut v = Vec::new();
    walk(root, &mut v);
    v
}

fn render_command(out: &mut String, cmd: &Command, is_root: bool) {
    let path = bin_name(cmd);
    let _ = writeln!(out, "## `{path}`");
    let _ = writeln!(out);
    let long = long_about(cmd);
    if !long.is_empty() {
        let _ = writeln!(out, "{}", escape_html(&long));
        let _ = writeln!(out);
    }
    let usage = cmd.clone().render_usage().to_string();
    let usage = usage.trim_start_matches("Usage:").trim();
    let _ = writeln!(out, "```text");
    let _ = writeln!(out, "{usage}");
    let _ = writeln!(out, "```");
    let _ = writeln!(out);

    let subs: Vec<&Command> = cmd
        .get_subcommands()
        .filter(|s| !s.is_hide_set() && s.get_name() != "help")
        .collect();
    // The root's subcommands are the Commands table above; do not list them
    // twice.
    if !subs.is_empty() && !is_root {
        let _ = writeln!(out, "Subcommands:");
        let _ = writeln!(out);
        for s in subs {
            let p = bin_name(s);
            let _ = writeln!(out, "- [`{}`](#{}) — {}", p, anchor(&p), cell(&about(s)));
        }
        let _ = writeln!(out);
    }

    let positionals: Vec<&Arg> = cmd
        .get_positionals()
        .filter(|a| !a.is_hide_set())
        .collect();
    if !positionals.is_empty() {
        let _ = writeln!(out, "| Argument | Required | Default | Description |");
        let _ = writeln!(out, "|---|---|---|---|");
        for a in positionals {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} |",
                value_name(a),
                if a.is_required_set() { "yes" } else { "no" },
                cell(&defaults(a)),
                cell(&help(a))
            );
        }
        let _ = writeln!(out);
    }

    let flags: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| !a.is_positional() && !a.is_hide_set() && !is_builtin(a))
        .collect();
    if !flags.is_empty() {
        let _ = writeln!(out, "| Flag | Value | Default | Description |");
        let _ = writeln!(out, "|---|---|---|---|");
        for a in flags {
            let mut names = Vec::new();
            if let Some(s) = a.get_short() {
                names.push(format!("`-{s}`"));
            }
            if let Some(l) = a.get_long() {
                names.push(format!("`--{l}`"));
            }
            let names = names.join(", ");
            let mut desc = help(a);
            let possible = possible_values(a);
            if !possible.is_empty() {
                let _ = write!(desc, " [possible values: {possible}]");
            }
            if a.is_required_set() {
                desc.push_str(" [required]");
            }
            let _ = writeln!(
                out,
                "| {} | {} | {} | {} |",
                names,
                cell(&flag_value(a)),
                cell(&defaults(a)),
                cell(&desc)
            );
        }
        let _ = writeln!(out);
    }
}

fn is_builtin(a: &Arg) -> bool {
    matches!(a.get_id().as_str(), "help" | "version")
}

fn bin_name(cmd: &Command) -> String {
    cmd.get_bin_name().unwrap_or_else(|| cmd.get_name()).to_string()
}

/// GitHub's heading anchor: lowercase, spaces to `-`, punctuation dropped.
fn anchor(path: &str) -> String {
    path.chars()
        .filter_map(|c| match c {
            ' ' => Some('-'),
            c if c.is_ascii_alphanumeric() || c == '-' || c == '_' => Some(c.to_ascii_lowercase()),
            _ => None,
        })
        .collect()
}

fn about(cmd: &Command) -> String {
    cmd.get_about().map(|s| s.to_string()).unwrap_or_default()
}

fn long_about(cmd: &Command) -> String {
    cmd.get_long_about()
        .or_else(|| cmd.get_about())
        .map(|s| s.to_string())
        .unwrap_or_default()
}

fn help(a: &Arg) -> String {
    a.get_long_help()
        .or_else(|| a.get_help())
        .map(|s| s.to_string())
        .unwrap_or_default()
}

fn value_name(a: &Arg) -> String {
    match a.get_value_names() {
        Some(names) if !names.is_empty() => {
            names.iter().map(|n| format!("<{n}>")).collect::<Vec<_>>().join(" ")
        }
        _ => format!("<{}>", a.get_id().as_str().to_ascii_uppercase()),
    }
}

fn is_switch(a: &Arg) -> bool {
    matches!(a.get_action(), ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Count)
}

/// What a flag takes: nothing for a switch; otherwise `` `<NAME>` `` (the
/// angle brackets must be code, or a Markdown table renders them as an HTML
/// tag and drops them), noting a repeatable flag and one whose value may be
/// omitted (`--csha` alone means `--csha auto`; `--training-report=json`
/// needs the `=`).
fn flag_value(a: &Arg) -> String {
    if is_switch(a) {
        return String::new();
    }
    let mut v = format!("`{}`", value_name(a));
    if matches!(a.get_action(), ArgAction::Append) {
        v.push_str(" (repeatable)");
    }
    if a.get_num_args().is_some_and(|n| n.min_values() == 0) {
        // clap 4.6 has no getter for the value a bare flag takes
        // (`default_missing_value`); the help text says it where it matters.
        v.push_str(" (optional");
        if a.is_require_equals_set() {
            v.push_str("; give a value as `=VALUE`");
        }
        v.push(')');
    }
    v
}

/// The default clap applies when the flag is absent. A switch's `false` is
/// not information (the help text does not print it either).
fn defaults(a: &Arg) -> String {
    if is_switch(a) {
        return String::new();
    }
    let d: Vec<String> = a
        .get_default_values()
        .iter()
        .map(|v| format!("`{}`", v.to_string_lossy()))
        .collect();
    d.join(", ")
}

fn possible_values(a: &Arg) -> String {
    let pv = a.get_possible_values();
    pv.iter()
        .filter(|p| !p.is_hide_set())
        .map(|p| format!("`{}`", p.get_name()))
        .collect::<Vec<_>>()
        .join(", ")
}

/// One table cell: no raw newlines or pipes (a paragraph break becomes a
/// space; a pipe would split the cell), angle brackets escaped.
fn cell(s: &str) -> String {
    let joined = s
        .split('\n')
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    escape_html(&joined).replace('|', "\\|")
}

/// Help text says `<file>.proof` and `<model>.cep.json`; outside a code span
/// Markdown reads those as HTML tags and drops them. Escape `<` and `>`
/// between backticks' code spans only, so `` `--csha <MODE>` `` stays code.
/// An unclosed backtick is not a code span (Markdown renders it literally),
/// so with an odd count the whole string is escaped.
fn escape_html(s: &str) -> String {
    if s.matches('`').count() % 2 == 1 {
        return s.replace('<', "&lt;").replace('>', "&gt;");
    }
    let mut out = String::with_capacity(s.len());
    for (i, piece) in s.split('`').enumerate() {
        if i > 0 {
            out.push('`');
        }
        if i % 2 == 0 {
            out.push_str(&piece.replace('<', "&lt;").replace('>', "&gt;"));
        } else {
            out.push_str(piece);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    fn workspace_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("workspace root")
    }

    #[test]
    fn wiki_page_is_the_command_tree_rendering() {
        let page = workspace_root().join("docs/wiki/CLI-Reference.md");
        let on_disk = std::fs::read_to_string(&page)
            .unwrap_or_else(|e| panic!("read {}: {e}", page.display()))
            .replace("\r\n", "\n");
        let rendered = render_markdown(&crate::args::Cli::command());
        if on_disk != rendered {
            let first_diff = on_disk
                .lines()
                .zip(rendered.lines())
                .position(|(a, b)| a != b)
                .map(|i| i + 1)
                .unwrap_or_else(|| on_disk.lines().count().min(rendered.lines().count()) + 1);
            panic!(
                "{} differs from `nsl doc cli` (first difference at line {first_diff}; on disk \
                 {} lines, rendered {}) — regenerate it:\n  cargo run -p nsl-cli -- doc cli > {}",
                page.display(),
                on_disk.lines().count(),
                rendered.lines().count(),
                page.display()
            );
        }
    }
}
