//! `nsl doc stdlib` — the standard-library reference, rendered from the
//! stdlib sources themselves (roadmap Doc3).
//!
//! `docs/wiki/Stdlib-Reference.md` is generated by this module and gated by
//! `wiki_page_is_the_stdlib_rendering` below — the same arrangement as
//! `docs/wiki/CLI-Reference.md` / `nsl doc cli` and
//! `docs/wiki/Environment-Variables.md` / `nsl env list --markdown`: the page
//! cannot drift from `stdlib/` because `cargo test -p nsl-cli` compares the
//! two.
//!
//! # Where each half of an entry comes from
//!
//! Signatures come from the **parser**, not from the text: a rendered
//! signature is what the compiler actually accepted, so a page entry cannot
//! describe a function the compiler would reject. Descriptions come from the
//! **lexer**, which already emits `##` doc comments as
//! [`TokenKind::DocComment`] and has done all along — the parser skips them
//! (`Parser::skip_newlines`), so nothing downstream ever saw them.
//!
//! The two are joined by span: a run of doc-comment tokens ending on the line
//! before an item's span belongs to that item. That deliberately avoids
//! adding a `docs` field to `FnDef`/`ModelDef`, which would have rewritten
//! every `*.ast.snap` in `nsl-parser` — a large diff in which a real AST
//! change could hide.
//!
//! # What counts as documented
//!
//! `#` is an ordinary comment and `##` is a doc comment. A module's leading
//! `##` block (before any item) is the module's own description. An item with
//! no `##` block is still listed — with its signature and no prose — because
//! a reference that silently omits undocumented API is worse than one that
//! shows the gap.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use nsl_ast::decl::ModelMember;
use nsl_ast::stmt::StmtKind;
use nsl_errors::FileId;
use nsl_lexer::{Interner, TokenKind};

/// One documented item: a free function, or a model with its layers and
/// methods.
struct Entry {
    /// Rendered signature, e.g. `fn clamp(x: float, lo: float, hi: float) -> float`.
    signature: String,
    /// The `##` block above it, one string per line, already stripped.
    docs: Vec<String>,
    /// Nested entries — a model's layer fields and methods.
    children: Vec<Entry>,
}

/// One stdlib module: `nsl.nn.losses` and everything it declares.
struct ModuleDoc {
    /// Dotted import path, e.g. `nsl.nn.losses`.
    path: String,
    /// Path relative to the stdlib root, e.g. `nsl/nn/losses.nsl`.
    file: String,
    /// The leading `##` block, if the file opens with one.
    docs: Vec<String>,
    entries: Vec<Entry>,
}

/// Collect every `##` run in the token stream, keyed by the line the run ENDS
/// on. An item is documented by the run ending on the line above it.
fn doc_runs(tokens: &[nsl_lexer::Token], src: &str) -> Vec<(usize, usize, Vec<String>)> {
    let line_of = line_index(src);
    let mut runs: Vec<(usize, usize, Vec<String>)> = Vec::new();
    for t in tokens {
        let TokenKind::DocComment(text) = &t.kind else {
            continue;
        };
        let line = line_of(t.span.start.0 as usize);
        match runs.last_mut() {
            // Contiguous with the previous doc line: same block.
            Some((_, end, lines)) if *end + 1 == line => {
                *end = line;
                lines.push(text.clone());
            }
            _ => runs.push((line, line, vec![text.clone()])),
        }
    }
    runs
}

/// A closure from byte offset to 0-based line number.
fn line_index(src: &str) -> impl Fn(usize) -> usize + '_ {
    let starts: Vec<usize> = std::iter::once(0)
        .chain(src.match_indices('\n').map(|(i, _)| i + 1))
        .collect();
    move |offset| match starts.binary_search(&offset) {
        Ok(i) => i,
        Err(i) => i - 1,
    }
}

/// The doc run immediately above `line`, if any, consuming it so a run cannot
/// be claimed by two items.
fn take_docs_above(runs: &mut Vec<(usize, usize, Vec<String>)>, line: usize) -> Vec<String> {
    let Some(i) = runs.iter().position(|(_, end, _)| end + 1 == line) else {
        return Vec::new();
    };
    runs.remove(i).2
}

/// Parse every module under `stdlib_root`, in a stable order.
///
/// Separate from [`render_markdown`] so a gate can assert something about the
/// PARSED modules rather than about the rendered text. A gate that greps the
/// output can only see what the renderer chose to emit, which is exactly the
/// blind spot that let a dropped item through.
fn collect_modules(stdlib_root: &Path) -> Result<Vec<ModuleDoc>, String> {
    let mut files: Vec<PathBuf> = Vec::new();
    collect_nsl_files(stdlib_root, &mut files)?;
    files.sort();

    let mut modules = Vec::new();
    for file in &files {
        modules.push(document_file(stdlib_root, file)?);
    }
    Ok(modules)
}

pub(crate) fn render_markdown(stdlib_root: &Path) -> Result<String, String> {
    let modules = collect_modules(stdlib_root)?;

    let fns: usize = modules.iter().map(|m| m.entries.iter().filter(|e| e.children.is_empty()).count()).sum();
    let models: usize = modules.iter().map(|m| m.entries.iter().filter(|e| !e.children.is_empty()).count()).sum();
    let undocumented: usize = modules
        .iter()
        .flat_map(|m| m.entries.iter())
        .filter(|e| e.docs.is_empty())
        .count();

    let mut out = String::new();
    let _ = writeln!(out, "# Standard library reference");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "<!-- GENERATED by `nsl doc stdlib` from stdlib/. Do not edit by hand: `cargo test -p \
         nsl-cli` fails if this page and the sources differ. -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Everything `stdlib/` declares: {} modules, {} free functions and {} models. Signatures \
         are rendered from the parser, so an entry here is what the compiler accepted, not what \
         a comment claims. Descriptions come from `##` doc comments in the source (`#` is an \
         ordinary comment and does not appear here); an item with no `##` block is listed with \
         its signature alone, so the gaps are visible rather than hidden.{}",
        modules.len(),
        fns,
        models,
        if undocumented > 0 {
            format!(" {undocumented} of them are currently undocumented.")
        } else {
            String::new()
        }
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Most of NSL's numeric surface is *language*, not library: tensor arithmetic, `matmul`, \
         `softmax`, `relu` and the rest are compiler builtins reached without an import. This \
         page covers only what is written in NSL itself and imported with `from <module> import \
         <name>`."
    );
    let _ = writeln!(out);

    // Index.
    let _ = writeln!(out, "## Modules");
    let _ = writeln!(out);
    for m in &modules {
        // The first SENTENCE, not the first line: module summaries wrap, and
        // `docs.first()` cut four of them mid-clause.
        let joined = m.docs.join(" ");
        let summary = match joined.find(". ") {
            Some(i) => &joined[..=i],
            None => joined.trim_end(),
        };
        if summary.is_empty() {
            let _ = writeln!(out, "- [`{}`](#{})", m.path, anchor(&m.path));
        } else {
            let _ = writeln!(out, "- [`{}`](#{}) — {}", m.path, anchor(&m.path), summary);
        }
    }
    let _ = writeln!(out);

    for m in &modules {
        let _ = writeln!(out, "## `{}`", m.path);
        let _ = writeln!(out);
        let _ = writeln!(out, "*Source: `stdlib/{}`*", m.file);
        let _ = writeln!(out);
        if !m.docs.is_empty() {
            for line in &m.docs {
                let _ = writeln!(out, "{line}");
            }
            let _ = writeln!(out);
        }
        if m.entries.is_empty() {
            let _ = writeln!(out, "This module declares no importable items.");
            let _ = writeln!(out);
            continue;
        }
        for e in &m.entries {
            render_entry(&mut out, e, 3);
        }
    }
    Ok(out)
}

fn render_entry(out: &mut String, e: &Entry, depth: usize) {
    let hashes = "#".repeat(depth);
    let _ = writeln!(out, "{hashes} `{}`", e.signature);
    let _ = writeln!(out);
    if e.docs.is_empty() {
        // Only a top-level item is marked as a hole. A model's fields and
        // methods are nested under an entry that already describes them, and
        // a field's type is usually the whole of its documentation — marking
        // 56 of those "*Undocumented.*" made the page look threadbare and
        // buried the gaps that matter. `every_stdlib_item_carries_a_doc_comment`
        // gates exactly this set.
        if depth == 3 {
            let _ = writeln!(out, "*Undocumented.*");
            let _ = writeln!(out);
        }
    } else {
        for line in &e.docs {
            let _ = writeln!(out, "{line}");
        }
        let _ = writeln!(out);
    }
    for c in &e.children {
        render_entry(out, c, depth + 1);
    }
}

/// GitHub's heading slug: lowercase, spaces to hyphens, everything else that
/// is not alphanumeric/hyphen/underscore removed. `nsl.compat` becomes
/// `nslcompat`, NOT `nsl-compat` — the same rule `cli_reference::anchor`
/// applies, kept identical on purpose so the two pages link alike.
fn anchor(path: &str) -> String {
    path.chars()
        .filter_map(|c| match c {
            ' ' => Some('-'),
            'a'..='z' | '0'..='9' | '-' | '_' => Some(c),
            'A'..='Z' => Some(c.to_ascii_lowercase()),
            _ => None,
        })
        .collect()
}

fn collect_nsl_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let rd = std::fs::read_dir(dir).map_err(|e| format!("read {}: {e}", dir.display()))?;
    for entry in rd {
        let entry = entry.map_err(|e| format!("read {}: {e}", dir.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_nsl_files(&path, out)?;
        } else if path.extension().is_some_and(|x| x == "nsl") {
            out.push(path);
        }
    }
    Ok(())
}

fn document_file(root: &Path, file: &Path) -> Result<ModuleDoc, String> {
    let src = std::fs::read_to_string(file)
        .map_err(|e| format!("read {}: {e}", file.display()))?
        .replace("\r\n", "\n");
    let rel = file
        .strip_prefix(root)
        .map_err(|_| format!("{} is not under {}", file.display(), root.display()))?;
    let rel_str = rel.to_string_lossy().replace('\\', "/");
    let path = rel_str
        .trim_end_matches(".nsl")
        .replace('/', ".");

    let mut interner = Interner::new();
    let (tokens, lex_diags) = nsl_lexer::tokenize(&src, FileId(0), &mut interner);
    let parsed = nsl_parser::parse(&tokens, &mut interner);

    // REFUSE rather than under-report. A file that does not parse yields an
    // empty statement list, and rendering that would silently drop every item
    // it declares — a reference page that is quietly missing a function is
    // worse than no page. This is how a stray edit to a doc comment (which
    // can break the file, `#` being a comment marker) gets caught.
    let fatal: Vec<&nsl_errors::Diagnostic> = lex_diags
        .iter()
        .chain(parsed.diagnostics.iter())
        .filter(|d| d.level == nsl_errors::Level::Error)
        .collect();
    if !fatal.is_empty() {
        return Err(format!(
            "{} does not parse ({} error{}); the reference cannot describe it. First: {}",
            file.display(),
            fatal.len(),
            if fatal.len() == 1 { "" } else { "s" },
            fatal[0].message,
        ));
    }

    let line_of = line_index(&src);
    let mut runs = doc_runs(&tokens, &src);

    // The module's own description is the first `##` block that no item
    // claims. Deliberately NOT "the run starting at line 0": several stdlib
    // files open with `from … import …`, and requiring line 0 silently denied
    // those files a module header. The run must also not be adjacent to the
    // first item, or it is that item's doc, not the module's.
    let first_item_line = parsed
        .module
        .stmts
        .iter()
        .map(|st| {
            let mut st = st;
            while let StmtKind::Decorated { stmt: inner, .. } = &st.kind {
                st = inner.as_ref();
            }
            st.span.start
        })
        .map(|p| line_of(p.0 as usize))
        .min();
    let module_docs = match (runs.first().map(|(s, e, _)| (*s, *e)), first_item_line) {
        (Some((_, end)), Some(item)) if end + 1 < item => runs.remove(0).2,
        (Some(_), None) => runs.remove(0).2,
        _ => Vec::new(),
    };

    let mut entries = Vec::new();
    for stmt in &parsed.module.stmts {
        // A decorated item (`@no_grad fn generate`) is wrapped, so unwrap
        // before matching — otherwise it falls through the catch-all and the
        // page silently omits it while claiming the module declares nothing.
        // The doc run is joined to the INNER item's line, because the `##`
        // block sits between the decorator and the `fn`.
        //
        // A visibility prefix wraps a decorated item in a SECOND `Decorated`
        // (`parse_visibility_prefixed` wrapping `parse_decorated_stmt`), so
        // this unwraps to a fixed point rather than once. The decorators are
        // collected on the way down: the page says its signatures are what
        // the compiler accepted, and `@no_grad` is part of that.
        // Rendered INLINE, not on their own lines: the signature becomes a
        // `###` heading, and a newline inside one breaks both the heading and
        // the anchor the index links to.
        let mut stmt = stmt;
        let mut decorators: Vec<String> = Vec::new();
        while let StmtKind::Decorated { decorators: d, stmt: inner } = &stmt.kind {
            for dec in d {
                let path: Vec<String> = dec.name.iter().map(|s| sym(&interner, *s)).collect();
                decorators.push(format!("@{}", path.join(".")));
            }
            stmt = inner.as_ref();
        }
        let prefix = if decorators.is_empty() {
            String::new()
        } else {
            format!("{} ", decorators.join(" "))
        };
        let line = line_of(stmt.span.start.0 as usize);
        match &stmt.kind {
            StmtKind::FnDef(f) => entries.push(Entry {
                signature: format!("{prefix}{}", render_fn_signature(f, &interner)),
                docs: take_docs_above(&mut runs, line),
                children: Vec::new(),
            }),
            StmtKind::ModelDef(m) => {
                let docs = take_docs_above(&mut runs, line);
                let mut children = Vec::new();
                for member in &m.members {
                    match member {
                        ModelMember::LayerDecl { name, type_ann, span, .. } => {
                            let l = line_of(span.start.0 as usize);
                            children.push(Entry {
                                signature: format!(
                                    "{}: {}",
                                    sym(&interner, *name),
                                    render_type(type_ann, &interner)
                                ),
                                docs: take_docs_above(&mut runs, l),
                                children: Vec::new(),
                            });
                        }
                        ModelMember::Method(f, _) => {
                            let l = line_of(f.span.start.0 as usize);
                            children.push(Entry {
                                signature: render_fn_signature(f, &interner),
                                docs: take_docs_above(&mut runs, l),
                                children: Vec::new(),
                            });
                        }
                    }
                }
                entries.push(Entry {
                    signature: format!("{prefix}{}", render_model_signature(m, &interner)),
                    docs,
                    children,
                });
            }
            // Not declarations — nothing to document.
            StmtKind::VarDecl { .. }
            | StmtKind::If { .. }
            | StmtKind::For { .. }
            | StmtKind::While { .. }
            | StmtKind::WhileLet { .. }
            | StmtKind::Match { .. }
            | StmtKind::Break
            | StmtKind::Continue
            | StmtKind::Return(_)
            | StmtKind::Yield(_)
            | StmtKind::Assign { .. }
            | StmtKind::Import(_)
            | StmtKind::FromImport(_)
            | StmtKind::TrainBlock(_)
            | StmtKind::DistillBlock(_)
            | StmtKind::GradBlock(_)
            | StmtKind::QuantBlock(_)
            | StmtKind::Expr(_) => {}

            // Declaration forms this renderer does not yet know how to show.
            // REFUSING is the point: the bug this replaced was a catch-all
            // that silently dropped `@no_grad fn generate`, and no gate could
            // see it — the drift gate compares the renderer to itself, and a
            // dropped item emits no "*Undocumented.*" line. There is no
            // exhaustive match over the INPUT anywhere else, so this arm is
            // the only thing that turns "stdlib grew a form we don't render"
            // into a failure rather than a hole. None of these appear in
            // `stdlib/` today; the first one to be added must teach the
            // renderer about it.
            StmtKind::AgentDef(_)
            | StmtKind::StructDef(_)
            | StmtKind::EnumDef(_)
            | StmtKind::TraitDef(_)
            | StmtKind::KernelDef(_)
            | StmtKind::TokenizerDef(_)
            | StmtKind::DatasetDef(_)
            | StmtKind::DatatypeDef(_)
            | StmtKind::ServeBlock(_) => {
                return Err(format!(
                    "{}: top-level {} is a declaration this reference does not render. \
                     Teach `stdlib_reference.rs` to render it rather than letting the page \
                     omit it silently.",
                    file.display(),
                    stmt_kind_name(&stmt.kind),
                ));
            }

            // Unwrapped to a fixed point above.
            StmtKind::Decorated { .. } => unreachable!("decorators unwrapped above"),
        }
    }

    Ok(ModuleDoc { path, file: rel_str, docs: module_docs, entries })
}

/// The spelling of a statement kind, for the refusal message above.
fn stmt_kind_name(kind: &StmtKind) -> &'static str {
    match kind {
        StmtKind::AgentDef(_) => "`agent`",
        StmtKind::StructDef(_) => "`struct`",
        StmtKind::EnumDef(_) => "`enum`",
        StmtKind::TraitDef(_) => "`trait`",
        StmtKind::KernelDef(_) => "`kernel`",
        StmtKind::TokenizerDef(_) => "`tokenizer`",
        StmtKind::DatasetDef(_) => "`dataset`",
        StmtKind::DatatypeDef(_) => "`datatype`",
        StmtKind::ServeBlock(_) => "`serve`",
        _ => "declaration",
    }
}

fn render_fn_signature(f: &nsl_ast::decl::FnDef, interner: &Interner) -> String {
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| match &p.type_ann {
            Some(t) => format!("{}: {}", sym(interner, p.name), render_type(t, interner)),
            None => sym(interner, p.name).to_string(),
        })
        .collect();
    let ret = match &f.return_type {
        Some(t) => format!(" -> {}", render_type(t, interner)),
        None => String::new(),
    };
    format!(
        "{}fn {}({}){ret}",
        if f.is_async { "async " } else { "" },
        sym(interner, f.name),
        params.join(", "),
    )
}

fn render_model_signature(m: &nsl_ast::decl::ModelDef, interner: &Interner) -> String {
    let params: Vec<String> = m
        .params
        .iter()
        .map(|p| match &p.type_ann {
            Some(t) => format!("{}: {}", sym(interner, p.name), render_type(t, interner)),
            None => sym(interner, p.name).to_string(),
        })
        .collect();
    format!("model {}({})", sym(interner, m.name), params.join(", "))
}

/// Render a type annotation the way the source spells it. Deliberately
/// structural rather than `Debug`: a reference page shows `Tensor`, not
/// `TypeExpr { kind: Named(...) }`.
fn render_type(t: &nsl_ast::types::TypeExpr, interner: &Interner) -> String {
    use nsl_ast::types::TypeExprKind as K;
    match &t.kind {
        K::Named(name) => sym(interner, *name),
        K::Generic { name, args } => format!(
            "{}<{}>",
            sym(interner, *name),
            args.iter().map(|a| render_type(a, interner)).collect::<Vec<_>>().join(", ")
        ),
        // Tensor types with shape/dtype/device, function types and the rest
        // are rare in the stdlib; render them structurally rather than
        // inventing a spelling that might not round-trip through the parser.
        other => format!("{other:?}"),
    }
}

/// Resolve an interned symbol, or a visible placeholder. The parser only
/// produces symbols it interned, so the `None` arm is unreachable in
/// practice — but a documentation tool must not panic on it.
fn sym(interner: &Interner, s: nsl_ast::Symbol) -> String {
    interner.resolve(s.0).unwrap_or("<unknown>").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("workspace root")
    }

    #[test]
    fn wiki_page_is_the_stdlib_rendering() {
        let root = workspace_root();
        let page = root.join("docs/wiki/Stdlib-Reference.md");
        let on_disk = std::fs::read_to_string(&page)
            .unwrap_or_else(|e| panic!("read {}: {e}", page.display()))
            .replace("\r\n", "\n");
        let rendered = render_markdown(&root.join("stdlib")).expect("render the stdlib reference");
        if on_disk != rendered {
            let first_diff = on_disk
                .lines()
                .zip(rendered.lines())
                .position(|(a, b)| a != b)
                .map(|i| i + 1)
                .unwrap_or_else(|| on_disk.lines().count().min(rendered.lines().count()) + 1);
            panic!(
                "{} differs from `nsl doc stdlib` (first difference at line {first_diff}; on disk \
                 {} lines, rendered {}) — regenerate it:\n  cargo run -p nsl-cli -- doc stdlib > {}",
                page.display(),
                on_disk.lines().count(),
                rendered.lines().count(),
                page.display()
            );
        }
    }

    /// Every TOP-LEVEL item — free function or model — carries a `##` block.
    ///
    /// The drift gate above cannot see this: if the span join ever broke,
    /// every entry would read "*Undocumented.*" and the regenerated page
    /// would still match the regenerated page. This is the gate that fails.
    ///
    /// Model fields and methods are deliberately NOT covered. They render
    /// under an entry that already describes them and a field's type is
    /// usually its whole documentation, so requiring prose on each would buy
    /// ceremony rather than information.
    #[test]
    fn every_top_level_stdlib_item_carries_a_doc_comment() {
        let rendered = render_markdown(&workspace_root().join("stdlib"))
            .expect("render the stdlib reference");
        let undocumented: Vec<&str> = rendered
            .lines()
            .collect::<Vec<_>>()
            .windows(3)
            .filter(|w| w[0].starts_with("### ") && w[2] == "*Undocumented.*")
            .map(|w| w[0])
            .collect();
        assert!(
            undocumented.is_empty(),
            "{} top-level stdlib item(s) have no `##` doc comment — write one, \
             or the reference page carries a hole:\n  {}",
            undocumented.len(),
            undocumented.join("\n  ")
        );
    }

    /// Every module carries a header.
    ///
    /// Module headers are detected by a rule with a silent failure mode — a
    /// `##` run ADJACENT to the file's first statement is treated as that
    /// item's doc, not the module's, and if no item claims it (an `import`
    /// is not an entry) it is dropped. That is how six modules went
    /// headerless through #590 unnoticed. The item gate above cannot see it:
    /// a module with no description emits no "*Undocumented.*" line, it just
    /// renders a heading with nothing under it.
    #[test]
    fn every_stdlib_module_carries_a_header() {
        let modules = collect_modules(&workspace_root().join("stdlib"))
            .expect("collect the stdlib modules");
        let headerless: Vec<String> = modules
            .iter()
            .filter(|m| m.docs.is_empty())
            .map(|m| m.file.clone())
            .collect();
        assert!(
            headerless.is_empty(),
            "{} stdlib module(s) have no `##` header. Put a `##` block at the top of the \
             file, separated from the first declaration by a blank line — a run adjacent to \
             the first item belongs to that item:\n  {}",
            headerless.len(),
            headerless.join("\n  ")
        );
    }
}
