//! `nsl doc stdlib` — the standard-library reference, rendered from the
//! stdlib sources themselves (roadmap Doc3).
//!
//! `docs/wiki/Stdlib-Reference.md` is generated by this module and gated by
//! `wiki_page_is_the_stdlib_rendering` below — the same arrangement as
//! `docs/wiki/CLI-Reference.md` / `nsl doc cli` and
//! `docs/wiki/Environment-Variables.md` / `nsl env list --markdown`: the page
//! cannot drift from `stdlib/` because `cargo test -p nsl-cli` compares the
//! two.
//!
//! # Where each half of an entry comes from
//!
//! Signatures come from the **parser**, not from the text: a rendered
//! signature is what the compiler actually accepted, so a page entry cannot
//! describe a function the compiler would reject. Descriptions come from the
//! **lexer**, which already emits `##` doc comments as
//! [`TokenKind::DocComment`] and has done all along — the parser skips them
//! (`Parser::skip_newlines`), so nothing downstream ever saw them.
//!
//! The two are joined by span: a run of doc-comment tokens ending on the line
//! before an item's span belongs to that item. That deliberately avoids
//! adding a `docs` field to `FnDef`/`ModelDef`, which would have rewritten
//! every `*.ast.snap` in `nsl-parser` — a large diff in which a real AST
//! change could hide.
//!
//! # What counts as documented
//!
//! `#` is an ordinary comment and `##` is a doc comment. A module's leading
//! `##` block (before any item) is the module's own description. An item with
//! no `##` block is still listed — with its signature and no prose — because
//! a reference that silently omits undocumented API is worse than one that
//! shows the gap.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use nsl_ast::decl::ModelMember;
use nsl_ast::stmt::StmtKind;
use nsl_errors::FileId;
use nsl_lexer::{Interner, TokenKind};

/// One documented item: a free function, or a model with its layers and
/// methods.
struct Entry {
    /// Rendered signature, e.g. `fn clamp(x: float, lo: float, hi: float) -> float`.
    signature: String,
    /// The `##` block above it, one string per line, already stripped.
    docs: Vec<String>,
    /// Nested entries — a model's layer fields and methods.
    children: Vec<Entry>,
}

/// One stdlib module: `nsl.nn.losses` and everything it declares.
struct ModuleDoc {
    /// Dotted import path, e.g. `nsl.nn.losses`.
    path: String,
    /// Path relative to the stdlib root, e.g. `nsl/nn/losses.nsl`.
    file: String,
    /// The leading `##` block, if the file opens with one.
    docs: Vec<String>,
    entries: Vec<Entry>,
}

/// Collect every `##` run in the token stream, keyed by the line the run ENDS
/// on. An item is documented by the run ending on the line above it.
fn doc_runs(tokens: &[nsl_lexer::Token], src: &str) -> Vec<(usize, usize, Vec<String>)> {
    let line_of = line_index(src);
    let mut runs: Vec<(usize, usize, Vec<String>)> = Vec::new();
    for t in tokens {
        let TokenKind::DocComment(text) = &t.kind else {
            continue;
        };
        let line = line_of(t.span.start.0 as usize);
        match runs.last_mut() {
            // Contiguous with the previous doc line: same block.
            Some((_, end, lines)) if *end + 1 == line => {
                *end = line;
                lines.push(text.clone());
            }
            _ => runs.push((line, line, vec![text.clone()])),
        }
    }
    runs
}

/// A closure from byte offset to 0-based line number.
fn line_index(src: &str) -> impl Fn(usize) -> usize + '_ {
    let starts: Vec<usize> = std::iter::once(0)
        .chain(src.match_indices('\n').map(|(i, _)| i + 1))
        .collect();
    move |offset| match starts.binary_search(&offset) {
        Ok(i) => i,
        Err(i) => i - 1,
    }
}

/// The doc run immediately above `line`, if any, consuming it so a run cannot
/// be claimed by two items.
fn take_docs_above(runs: &mut Vec<(usize, usize, Vec<String>)>, line: usize) -> Vec<String> {
    let Some(i) = runs.iter().position(|(_, end, _)| end + 1 == line) else {
        return Vec::new();
    };
    runs.remove(i).2
}

pub(crate) fn render_markdown(stdlib_root: &Path) -> Result<String, String> {
    let mut files: Vec<PathBuf> = Vec::new();
    collect_nsl_files(stdlib_root, &mut files)?;
    files.sort();

    let mut modules = Vec::new();
    for file in &files {
        modules.push(document_file(stdlib_root, file)?);
    }

    let fns: usize = modules.iter().map(|m| m.entries.iter().filter(|e| e.children.is_empty()).count()).sum();
    let models: usize = modules.iter().map(|m| m.entries.iter().filter(|e| !e.children.is_empty()).count()).sum();
    let undocumented: usize = modules
        .iter()
        .flat_map(|m| m.entries.iter())
        .filter(|e| e.docs.is_empty())
        .count();

    let mut out = String::new();
    let _ = writeln!(out, "# Standard library reference");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "<!-- GENERATED by `nsl doc stdlib` from stdlib/. Do not edit by hand: `cargo test -p \
         nsl-cli` fails if this page and the sources differ. -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Everything `stdlib/` declares: {} modules, {} free functions and {} models. Signatures \
         are rendered from the parser, so an entry here is what the compiler accepted, not what \
         a comment claims. Descriptions come from `##` doc comments in the source (`#` is an \
         ordinary comment and does not appear here); an item with no `##` block is listed with \
         its signature alone, so the gaps are visible rather than hidden.{}",
        modules.len(),
        fns,
        models,
        if undocumented > 0 {
            format!(" {undocumented} of them are currently undocumented.")
        } else {
            String::new()
        }
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Most of NSL's numeric surface is *language*, not library: tensor arithmetic, `matmul`, \
         `softmax`, `relu` and the rest are compiler builtins reached without an import. This \
         page covers only what is written in NSL itself and imported with `from <module> import \
         <name>`."
    );
    let _ = writeln!(out);

    // Index.
    let _ = writeln!(out, "## Modules");
    let _ = writeln!(out);
    for m in &modules {
        let summary = m.docs.first().map(String::as_str).unwrap_or("");
        let _ = writeln!(out, "- [`{}`](#{}) — {}", m.path, anchor(&m.path), summary);
    }
    let _ = writeln!(out);

    for m in &modules {
        let _ = writeln!(out, "## `{}`", m.path);
        let _ = writeln!(out);
        let _ = writeln!(out, "*Source: `stdlib/{}`*", m.file);
        let _ = writeln!(out);
        if !m.docs.is_empty() {
            for line in &m.docs {
                let _ = writeln!(out, "{line}");
            }
            let _ = writeln!(out);
        }
        if m.entries.is_empty() {
            let _ = writeln!(out, "This module declares no importable items.");
            let _ = writeln!(out);
            continue;
        }
        for e in &m.entries {
            render_entry(&mut out, e, 3);
        }
    }
    Ok(out)
}

fn render_entry(out: &mut String, e: &Entry, depth: usize) {
    let hashes = "#".repeat(depth);
    let _ = writeln!(out, "{hashes} `{}`", e.signature);
    let _ = writeln!(out);
    if e.docs.is_empty() {
        let _ = writeln!(out, "*Undocumented.*");
    } else {
        for line in &e.docs {
            let _ = writeln!(out, "{line}");
        }
    }
    let _ = writeln!(out);
    for c in &e.children {
        render_entry(out, c, depth + 1);
    }
}

fn anchor(path: &str) -> String {
    path.chars()
        .filter_map(|c| match c {
            'a'..='z' | '0'..='9' | '-' => Some(c),
            'A'..='Z' => Some(c.to_ascii_lowercase()),
            '.' | '_' => Some('-'),
            _ => None,
        })
        .collect()
}

fn collect_nsl_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let rd = std::fs::read_dir(dir).map_err(|e| format!("read {}: {e}", dir.display()))?;
    for entry in rd {
        let entry = entry.map_err(|e| format!("read {}: {e}", dir.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_nsl_files(&path, out)?;
        } else if path.extension().is_some_and(|x| x == "nsl") {
            out.push(path);
        }
    }
    Ok(())
}

fn document_file(root: &Path, file: &Path) -> Result<ModuleDoc, String> {
    let src = std::fs::read_to_string(file)
        .map_err(|e| format!("read {}: {e}", file.display()))?
        .replace("\r\n", "\n");
    let rel = file
        .strip_prefix(root)
        .map_err(|_| format!("{} is not under {}", file.display(), root.display()))?;
    let rel_str = rel.to_string_lossy().replace('\\', "/");
    let path = rel_str
        .trim_end_matches(".nsl")
        .replace('/', ".");

    let mut interner = Interner::new();
    let (tokens, lex_diags) = nsl_lexer::tokenize(&src, FileId(0), &mut interner);
    let parsed = nsl_parser::parse(&tokens, &mut interner);

    // REFUSE rather than under-report. A file that does not parse yields an
    // empty statement list, and rendering that would silently drop every item
    // it declares — a reference page that is quietly missing a function is
    // worse than no page. This is how a stray edit to a doc comment (which
    // can break the file, `#` being a comment marker) gets caught.
    let fatal: Vec<&nsl_errors::Diagnostic> = lex_diags
        .iter()
        .chain(parsed.diagnostics.iter())
        .filter(|d| d.level == nsl_errors::Level::Error)
        .collect();
    if !fatal.is_empty() {
        return Err(format!(
            "{} does not parse ({} error{}); the reference cannot describe it. First: {}",
            file.display(),
            fatal.len(),
            if fatal.len() == 1 { "" } else { "s" },
            fatal[0].message,
        ));
    }

    let line_of = line_index(&src);
    let mut runs = doc_runs(&tokens, &src);

    // A `##` block at the very top of the file, with no item above it, is the
    // module's own description.
    let module_docs = if runs.first().is_some_and(|(start, _, _)| *start == 0) {
        runs.remove(0).2
    } else {
        Vec::new()
    };

    let mut entries = Vec::new();
    for stmt in &parsed.module.stmts {
        let line = line_of(stmt.span.start.0 as usize);
        match &stmt.kind {
            StmtKind::FnDef(f) => entries.push(Entry {
                signature: render_fn_signature(f, &interner),
                docs: take_docs_above(&mut runs, line),
                children: Vec::new(),
            }),
            StmtKind::ModelDef(m) => {
                let docs = take_docs_above(&mut runs, line);
                let mut children = Vec::new();
                for member in &m.members {
                    match member {
                        ModelMember::LayerDecl { name, type_ann, span, .. } => {
                            let l = line_of(span.start.0 as usize);
                            children.push(Entry {
                                signature: format!(
                                    "{}: {}",
                                    sym(&interner, *name),
                                    render_type(type_ann, &interner)
                                ),
                                docs: take_docs_above(&mut runs, l),
                                children: Vec::new(),
                            });
                        }
                        ModelMember::Method(f, _) => {
                            let l = line_of(f.span.start.0 as usize);
                            children.push(Entry {
                                signature: render_fn_signature(f, &interner),
                                docs: take_docs_above(&mut runs, l),
                                children: Vec::new(),
                            });
                        }
                    }
                }
                entries.push(Entry {
                    signature: render_model_signature(m, &interner),
                    docs,
                    // A model with no members would otherwise be rendered as a
                    // free function; give it one empty child so the shape is
                    // unambiguous to the counter above.
                    children,
                });
            }
            _ => {}
        }
    }

    Ok(ModuleDoc { path, file: rel_str, docs: module_docs, entries })
}

fn render_fn_signature(f: &nsl_ast::decl::FnDef, interner: &Interner) -> String {
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| match &p.type_ann {
            Some(t) => format!("{}: {}", sym(interner, p.name), render_type(t, interner)),
            None => sym(interner, p.name).to_string(),
        })
        .collect();
    let ret = match &f.return_type {
        Some(t) => format!(" -> {}", render_type(t, interner)),
        None => String::new(),
    };
    format!(
        "{}fn {}({}){ret}",
        if f.is_async { "async " } else { "" },
        sym(interner, f.name),
        params.join(", "),
    )
}

fn render_model_signature(m: &nsl_ast::decl::ModelDef, interner: &Interner) -> String {
    let params: Vec<String> = m
        .params
        .iter()
        .map(|p| match &p.type_ann {
            Some(t) => format!("{}: {}", sym(interner, p.name), render_type(t, interner)),
            None => sym(interner, p.name).to_string(),
        })
        .collect();
    format!("model {}({})", sym(interner, m.name), params.join(", "))
}

/// Render a type annotation the way the source spells it. Deliberately
/// structural rather than `Debug`: a reference page shows `Tensor`, not
/// `TypeExpr { kind: Named(...) }`.
fn render_type(t: &nsl_ast::types::TypeExpr, interner: &Interner) -> String {
    use nsl_ast::types::TypeExprKind as K;
    match &t.kind {
        K::Named(name) => sym(interner, *name),
        K::Generic { name, args } => format!(
            "{}<{}>",
            sym(interner, *name),
            args.iter().map(|a| render_type(a, interner)).collect::<Vec<_>>().join(", ")
        ),
        // Tensor types with shape/dtype/device, function types and the rest
        // are rare in the stdlib; render them structurally rather than
        // inventing a spelling that might not round-trip through the parser.
        other => format!("{other:?}"),
    }
}

/// Resolve an interned symbol, or a visible placeholder. The parser only
/// produces symbols it interned, so the `None` arm is unreachable in
/// practice — but a documentation tool must not panic on it.
fn sym(interner: &Interner, s: nsl_ast::Symbol) -> String {
    interner.resolve(s.0).unwrap_or("<unknown>").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("workspace root")
    }

    #[test]
    fn wiki_page_is_the_stdlib_rendering() {
        let root = workspace_root();
        let page = root.join("docs/wiki/Stdlib-Reference.md");
        let on_disk = std::fs::read_to_string(&page)
            .unwrap_or_else(|e| panic!("read {}: {e}", page.display()))
            .replace("\r\n", "\n");
        let rendered = render_markdown(&root.join("stdlib")).expect("render the stdlib reference");
        if on_disk != rendered {
            let first_diff = on_disk
                .lines()
                .zip(rendered.lines())
                .position(|(a, b)| a != b)
                .map(|i| i + 1)
                .unwrap_or_else(|| on_disk.lines().count().min(rendered.lines().count()) + 1);
            panic!(
                "{} differs from `nsl doc stdlib` (first difference at line {first_diff}; on disk \
                 {} lines, rendered {}) — regenerate it:\n  cargo run -p nsl-cli -- doc stdlib > {}",
                page.display(),
                on_disk.lines().count(),
                rendered.lines().count(),
                page.display()
            );
        }
    }

    /// The page exists to show what is documented AND what is not, so the
    /// generator must actually attach `##` blocks to items. If the joining
    /// ever breaks, every entry silently becomes "*Undocumented.*" and the
    /// gate above would still pass — the regenerated page would just match
    /// the regenerated page. This pins that the stdlib is in fact documented.
    #[test]
    fn every_stdlib_item_carries_a_doc_comment() {
        let rendered = render_markdown(&workspace_root().join("stdlib"))
            .expect("render the stdlib reference");
        let undocumented: Vec<&str> = rendered
            .lines()
            .collect::<Vec<_>>()
            .windows(3)
            .filter(|w| w[0].starts_with("### ") && w[2] == "*Undocumented.*")
            .map(|w| w[0])
            .collect();
        assert!(
            undocumented.is_empty(),
            "{} stdlib item(s) have no `##` doc comment — write one, or the \
             reference page carries a hole:\n  {}",
            undocumented.len(),
            undocumented.join("\n  ")
        );
    }
}
