#!/usr/bin/env bash
#
# gpu-cert.sh — the GPU certification lane (roadmap item 19).
#
# Before this script existed, the repository carried 295 `#[ignore]` tests, of
# which ~190 require a CUDA device, and .github/workflows/ci.yml contained
# ZERO jobs that run on real hardware. The one CUDA job there is named
# "CUDA feature — compile + GPU-free tests": it links against cudart STUBS and
# runs a ptxas syntax check. Nothing executed on a device, ever, in CI.
#
# That means every gate certifying flash-attention backward, CSHA, PCA, CFIE,
# ZeRO collectives, weight streaming, SR-BF16, Muon, CUDA graphs and the
# tensor-lifetime leak fixes only ran when a human remembered to type the
# command. This script is that human's replacement.
#
# PRIOR ART: tools/gpu-test.ps1 + tools/gpu-canary.txt already existed. Two
# reasons it is not enough, neither of them a criticism of its design:
#   - the canary is a deliberately CURATED set ("if they pass, the harness
#     itself is working") — an acceptance check, not coverage;
#   - it is PowerShell, and the project's dev environment moved to Linux where
#     pwsh is not installed, so it cannot run at all on the reference machine.
# This script is complementary: it enumerates and runs EVERYTHING, in bash.
# The canary keeps its job as the fast is-the-GPU-sane check — it is the
# `smoke` tier of scripts/gpu-tier.sh, and this lane is the `certify` tier.
#
# Usage:
#   scripts/gpu-cert.sh --list                  inventory as TSV, no build
#   scripts/gpu-cert.sh --check-inventory       drift gate (GPU-free, for CI)
#   scripts/gpu-cert.sh --check-long-arms       timeout-override gate (GPU-free)
#   scripts/gpu-cert.sh --write-manifest        refresh the committed manifest
#   scripts/gpu-cert.sh --run [--tier TIER]     build + execute the lane
#
# --run honours:
#   NSL_CERT_TIER      gpu | toolchain | multiproc | isolate | all  (default: gpu)
#   NSL_CERT_TIMEOUT   PER-GATE timeout in seconds (default: 1200). Targets
#                      named in ci/gpu-cert-long-arms.txt get the LARGER of
#                      this and their entry -- the full-training gates need
#                      ~1800s, and when the budget is short the gate reports
#                      TIMEOUT, which reads identically to a hung kernel.
#   NSL_CERT_BATCH_TIMEOUT
#                      ceiling for a target's batched run, which carries ALL of
#                      that target's gates in one `cargo test` (default: 3600).
#                      The batched budget is the per-gate value x gate-count,
#                      clamped to this. One shared number served both roles,
#                      which is wrong in principle -- a target's batch has to
#                      fit every gate it carries, a single rerun only one -- and
#                      leaves very little headroom in practice: measured on an
#                      RTX PRO 4500, `pretrain_loss_decrease_gpu_e2e` takes 530s
#                      of the old 900s, and `matmul_cublas_tf32_default_sanity`
#                      384s. Neither had room for a slower machine or a colder
#                      cache.
#   NSL_CERT_OUT       report path (default: target/gpu-cert-report.tsv)
#   NSL_CERT_FEATURES  cargo features
#                      (default: cuda,test-hooks,test-helpers,nsl-test/cuda)
#   CARGO_TARGET_DIR   respected as usual
#
# --run refuses to start when the device is busy or another guarded run holds
# the lock — scripts/gpu-guard.sh, which also puts the lane in its own process
# group. NSL_GPU_GUARD=0 skips the guard (debugging it, not bypassing a
# refusal: the refusal means a result produced now would be untrustworthy).
#
# Report columns: file<TAB>test<TAB>status<TAB>elapsed. A '~' prefix on elapsed
# means the value is the whole TARGET's wall time, shared by every gate of a
# batched run; bare values come from the per-gate rerun path and are that gate's
# own time. NOTFOUND rows carry '-' for elapsed — nothing ran.
#
# Set TMPDIR to a DISK-backed path before a full run. Many gates spawn `nsl`
# builds; where /tmp is tmpfs the sweep exhausts it, and the resulting linker
# errors surface as generic "nsl run failed" panics that read like compiler
# bugs rather than a full disk.
#
# Exit status for --run is 1 if any gate FAILS that is not listed in
# ci/gpu-cert-known-red.txt, else 0. Pre-existing breakage therefore does not
# block, but a NEW regression does — the same posture as the doc-agreement
# gate added in 0a5246cd.

set -euo pipefail

# Byte-order collation for every `sort` below. Without this the manifest is not
# reproducible across machines: a UTF-8 locale gives punctuation no primary
# weight, so `muon.rs` sorts AFTER `muon_batch.rs`, while the C locale compares
# `.` (0x2E) < `_` (0x5F) and puts it first. The manifest is generated by one
# developer and diffed by CI, so the two orders disagree and --check-inventory
# reports permanent phantom drift — a one-row real change arrives as a
# move-pair, and re-running --write-manifest locally "fixes" it only until the
# next machine touches it.
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

AWK_RULES="scripts/gpu-gate-inventory.awk"
MANIFEST="ci/gpu-cert-manifest.tsv"
KNOWN_RED="ci/gpu-cert-known-red.txt"
LONG_ARMS="ci/gpu-cert-long-arms.txt"

# The per-gate default, in ONE place. `--check-long-arms` rejects any override
# at or below it (such a row is inert, since the budget is a max), and cmd_run
# uses it as the fallback -- two literals would let the validator bless rows
# that do nothing.
DEFAULT_PER_GATE_TIMEOUT=1200

# `cuda` alone is NOT enough to reach every gate. Seven gates live in files
# whose whole module is cfg'd on an extra feature — `test-hooks` (cuBLAS
# equivalence, FP8 dispatcher) or `test-helpers` (the fused-LM-CE e2e set,
# which calls into nsl-codegen internals). Without these the targets compile
# to ZERO tests and the gates silently do not exist. The first sweep reported
# them as NOTFOUND, which is exactly what that status is for.
#
# `nsl-test/cuda` is a CROSS-PACKAGE feature and it is load-bearing.
# nsl-codegen's own `cuda` feature is ["nsl-runtime/cuda", "dep:cudarc"] — it
# does NOT reach nsl-test, the shared diagnostic harness. Without it, four
# tier_b2 `*_b1_forward` gates take diagnostic_mode.rs's
# `#[cfg(not(feature = "cuda"))]` arm and panic with "FSource::B1Forward
# requires feature='cuda'" — reported as a kernel failure when the kernel was
# never reached. They pass once it is enabled.
CERT_FEATURES="${NSL_CERT_FEATURES:-cuda,test-hooks,test-helpers,nsl-test/cuda}"

# ---------------------------------------------------------------------------
# Inventory
# ---------------------------------------------------------------------------

# Emit "file<TAB>fn<TAB>class<TAB>reason" for every #[ignore] test in the tree.
# The cuda_gated flag is computed per file in the shell (awk would have to
# buffer the whole file to look ahead at the cfg attributes).
inventory() {
    local f gated
    while IFS= read -r f; do
        if grep -q 'feature = "cuda"' "${f}"; then gated=1; else gated=0; fi
        awk -v cuda_gated="${gated}" -f "${AWK_RULES}" "${f}"
    done < <(find crates -name '*.rs' -type f | sort)
}

# Map a source path to the cargo invocation that can run its tests.
# crates/<pkg>/tests/<target>.rs  -> -p <pkg> --test <target>
# crates/<pkg>/src/**.rs          -> -p <pkg> --lib
target_args() {
    local path="$1" pkg target
    pkg="$(printf '%s' "${path}" | cut -d/ -f2)"
    case "${path}" in
        crates/*/tests/*)
            target="$(basename "${path}" .rs)"
            printf -- '-p\n%s\n--test\n%s\n' "${pkg}" "${target}"
            ;;
        *)
            printf -- '-p\n%s\n--lib\n' "${pkg}"
            ;;
    esac
}

# Features are NOT uniform across the workspace. `cargo test -p <pkg>` REFUSES
# a feature the package does not define ("the package 'nsl-runtime' does not
# contain this feature: test-helpers") — only `--workspace` unifies them. So
# every per-target invocation gets the intersection of CERT_FEATURES with what
# that package actually declares. Getting this wrong is not subtle-but-benign:
# it made 114 gates report NOTFOUND on a sweep where only 7 were genuinely
# unreachable.
features_for_pkg() {
    local pkg="$1" manifest="crates/$1/Cargo.toml" out="" f dep
    [[ -f "${manifest}" ]] || { printf ''; return; }
    local feats
    IFS=',' read -r -a feats <<< "${CERT_FEATURES}"
    for f in "${feats[@]}"; do
        if [[ "${f}" == */* ]]; then
            # Cross-package feature `dep/feat`: valid iff this package actually
            # declares `dep` as a dependency, else cargo rejects the whole
            # invocation.
            dep="${f%%/*}"
            if grep -qE "^${dep}[ =]" "${manifest}"; then
                out="${out:+${out},}${f}"
            fi
        elif grep -qE "^${f} *=" "${manifest}"; then
            out="${out:+${out},}${f}"
        fi
    done
    printf '%s' "${out}"
}

classes_for_tier() {
    case "$1" in
        gpu)       printf 'gpu\ngpu-inferred\n' ;;
        toolchain) printf 'toolchain\n' ;;
        multiproc) printf 'multiproc\n' ;;
        isolate)   printf 'isolate\n' ;;
        all)       printf 'gpu\ngpu-inferred\ntoolchain\nmultiproc\nisolate\n' ;;
        *) echo "gpu-cert: unknown tier '$1'" >&2; exit 2 ;;
    esac
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

cmd_list() { inventory; }

cmd_write_manifest() {
    mkdir -p "$(dirname "${MANIFEST}")"
    {
        echo "# GPU certification gate manifest — generated by scripts/gpu-cert.sh"
        echo "# Regenerate with: scripts/gpu-cert.sh --write-manifest"
        echo "# Columns: file<TAB>test<TAB>class<TAB>reason"
        inventory
    } > "${MANIFEST}"
    echo "wrote ${MANIFEST} ($(inventory | wc -l) gates)"
}

# The GPU-free half of item 19: CI cannot execute these gates, but it CAN
# prove the inventory still matches the source. A gate that is deleted,
# renamed, or silently un-#[ignore]d changes this file; a stale manifest fails
# the build. Without it the lane would rot the moment someone moved a test.
cmd_check_inventory() {
    if [[ ! -f "${MANIFEST}" ]]; then
        echo "gpu-cert: ${MANIFEST} is missing — run --write-manifest" >&2
        exit 1
    fi
    # Script-global, not `local`: the EXIT trap runs after this function's
    # frame is gone, and under `set -u` a dead local makes the trap itself
    # fail — turning a PASSING check into exit 1.
    SCRATCH="$(mktemp)"
    trap 'rm -f "${SCRATCH:-}"' EXIT
    inventory > "${SCRATCH}"
    if ! diff -u <(grep -v '^#' "${MANIFEST}") "${SCRATCH}" > /dev/null; then
        echo "gpu-cert: GATE INVENTORY DRIFT — ${MANIFEST} is stale." >&2
        echo "" >&2
        diff -u <(grep -v '^#' "${MANIFEST}") "${SCRATCH}" | head -40 >&2
        echo "" >&2
        echo "If the change is intended, run: scripts/gpu-cert.sh --write-manifest" >&2
        exit 1
    fi
    echo "gpu-cert: inventory agrees with source ($(grep -cv '^#' "${MANIFEST}") gates)"
}

# ---------------------------------------------------------------------------
# Per-target timeout overrides (ci/gpu-cert-long-arms.txt)
# ---------------------------------------------------------------------------

# Populate LONG_ARM, keyed by the same target key `cmd_run` groups gates under
# (the newline-joined `target_args` output), so the lookup at launch time is a
# plain array hit with no path handling.
#
# Several source files collapse onto one `--lib` target, so the entries are
# unioned with max() rather than last-wins: a target inherits the longest
# budget any of its files asked for. Silently taking the last would make the
# effective value depend on file order in the data file.
# A target key ("-p nsl-cli --test foo ") as a filename. Kept to [A-Za-z0-9._-]
# so the result is safe on every filesystem the artifact is unpacked on.
slugify() {
    printf '%s' "$1" | tr -c 'A-Za-z0-9._-' '_' | sed 's/__*/_/g; s/^_//; s/_$//'
}

declare -A LONG_ARM=()
load_long_arms() {
    LONG_ARM=()
    [[ -f "${LONG_ARMS}" ]] || return 0
    local file secs key cur
    while IFS=$'\t' read -r file secs; do
        case "${file}" in ''|'#'*) continue ;; esac
        [[ -n "${secs}" ]] || continue
        key="$(target_args "${file}" | tr '\n' ' ')"
        cur="${LONG_ARM[${key}]:-0}"
        if [[ "${secs}" -gt "${cur}" ]]; then
            LONG_ARM["${key}"]="${secs}"
        fi
    done < "${LONG_ARMS}"
}

# Effective budget for a target: MAX of the global setting and any override.
# Max, not override — see the file header. An operator raising
# NSL_CERT_TIMEOUT for a debugging sweep must not be shortened by this table.
timeout_for() {
    local key="$1" base="$2" over
    over="${LONG_ARM[${key}]:-0}"
    if [[ "${over}" -gt "${base}" ]]; then printf '%s' "${over}"; else printf '%s' "${base}"; fi
}

# GPU-FREE validation of ci/gpu-cert-long-arms.txt, for the CI inventory job.
#
# Without this the file goes inert on the first test-file rename: the key stops
# matching any target, the override silently stops applying, and the gate
# starts reporting TIMEOUT again with nothing pointing at the cause. Checking
# column 1 against the manifest is the same trick `--check-inventory` uses to
# keep the manifest honest, applied one file over.
cmd_check_long_arms() {
    if [[ ! -f "${LONG_ARMS}" ]]; then
        echo "gpu-cert: ${LONG_ARMS} is missing" >&2
        exit 1
    fi
    if [[ ! -f "${MANIFEST}" ]]; then
        echo "gpu-cert: ${MANIFEST} is missing — run --write-manifest" >&2
        exit 1
    fi
    # Paths the lane actually executes. A path in a non-run class (broken,
    # diagnostic, unclassified) would never be launched, so an override on it
    # is dead weight that reads as coverage.
    local runnable
    runnable="$(awk -F'\t' '
        $3 ~ /^(gpu|gpu-inferred|toolchain|multiproc|isolate)$/ { print $1 }
    ' "${MANIFEST}" | sort -u)"

    local n=0 lineno=0 file secs bad=0
    while IFS= read -r raw; do
        lineno=$((lineno + 1))
        case "${raw}" in ''|'#'*) continue ;; esac
        # Exactly two tab-separated fields, no more.
        if [[ "$(awk -F'\t' '{print NF}' <<< "${raw}")" != "2" ]]; then
            echo "gpu-cert: ${LONG_ARMS}:${lineno}: expected 2 tab-separated fields: ${raw}" >&2
            bad=1; continue
        fi
        file="$(cut -f1 <<< "${raw}")"
        secs="$(cut -f2 <<< "${raw}")"
        if ! [[ "${secs}" =~ ^[0-9]+$ ]]; then
            echo "gpu-cert: ${LONG_ARMS}:${lineno}: '${secs}' is not an integer" >&2
            bad=1; continue
        fi
        if [[ "${secs}" -le "${DEFAULT_PER_GATE_TIMEOUT}" || "${secs}" -gt 7200 ]]; then
            echo "gpu-cert: ${LONG_ARMS}:${lineno}: ${secs}s outside (${DEFAULT_PER_GATE_TIMEOUT}, 7200]." >&2
            echo "          The budget is a MAX, so at or below ${DEFAULT_PER_GATE_TIMEOUT}s the" >&2
            echo "          default already wins and the row is inert." >&2
            bad=1; continue
        fi
        if ! grep -qxF "${file}" <<< "${runnable}"; then
            echo "gpu-cert: ${LONG_ARMS}:${lineno}: '${file}' is not a run-class row in" >&2
            echo "          ${MANIFEST} — renamed, deleted, or never executed. The" >&2
            echo "          override is inert; fix the path or drop the line." >&2
            bad=1; continue
        fi
        n=$((n + 1))
    done < "${LONG_ARMS}"
    [[ "${bad}" -eq 0 ]] || exit 1
    echo "gpu-cert: ${n} long-arm timeout override(s) valid"
}

# PREFLIGHT — the lane's most important guard.
#
# 55 of the run-class test files gate their body on a `cuda_available()` helper
# that returns false when NSL_SKIP_CUDA_TESTS is set or `nsl_cuda_init()`
# fails, and then `return;` — which libtest reports as **ok**. Without this
# check, `--run --tier gpu` on a box with no device, a wedged driver, or that
# variable exported prints "PASS 255", writes an all-green report, exits 0, and
# has executed ZERO kernels. That is precisely the failure the lane exists to
# prevent, and it is silent.
#
# tools/gpu-test.ps1 already refused to run for this reason ("NSL_SKIP_CUDA_TESTS
# makes every CUDA test early-return as a 'pass' … falsely report green"). The
# bash lane must not be the weaker of the two.
preflight() {
    local tier="$1"
    if [[ -n "${NSL_SKIP_CUDA_TESTS:-}" ]]; then
        echo "gpu-cert: REFUSING — NSL_SKIP_CUDA_TESTS is set. Every CUDA test" >&2
        echo "          early-returns as a PASS under it, so the sweep would" >&2
        echo "          report green having run nothing. Unset it and re-run." >&2
        exit 2
    fi
    case "${tier}" in
        gpu|isolate|multiproc|all)
            if [[ "${CUDA_VISIBLE_DEVICES-unset}" == "" ]]; then
                echo "gpu-cert: REFUSING — CUDA_VISIBLE_DEVICES is set to empty;" >&2
                echo "          no device is visible and every gate would skip-as-pass." >&2
                exit 2
            fi
            if ! command -v nvidia-smi > /dev/null 2>&1; then
                echo "gpu-cert: REFUSING — nvidia-smi not found; cannot prove a device" >&2
                echo "          is present, and a skip-as-pass sweep is worse than none." >&2
                exit 2
            fi
            if ! nvidia-smi -L 2>/dev/null | grep -q '^GPU '; then
                echo "gpu-cert: REFUSING — nvidia-smi lists no GPU." >&2
                exit 2
            fi
            echo "gpu-cert: device — $(nvidia-smi -L 2>/dev/null | head -1)"
            ;;
    esac
    if [[ "${tier}" == "toolchain" || "${tier}" == "all" ]]; then
        if ! command -v ptxas > /dev/null 2>&1; then
            echo "gpu-cert: REFUSING — ptxas not on PATH; toolchain gates print" >&2
            echo "          'ptxas not found — skipping' and report as PASS." >&2
            exit 2
        fi
    fi
}

cmd_run() {
    local tier="${NSL_CERT_TIER:-gpu}"
    local t0=0 t1=0   # hoisted: read by the report rows in both run paths
    local timeout_s="${NSL_CERT_TIMEOUT:-${DEFAULT_PER_GATE_TIMEOUT}}"
    local batch_cap="${NSL_CERT_BATCH_TIMEOUT:-3600}"
    local out="${NSL_CERT_OUT:-${CARGO_TARGET_DIR:-target}/gpu-cert-report.tsv}"
    mkdir -p "$(dirname "${out}")"

    # Durable per-gate logs beside the report. Everything the run produced used
    # to live in a mktemp dir that the EXIT trap deleted, so a failing gate left
    # exactly the three grep'd lines below in an Actions log that expires long
    # before the 90-day artifact — and a target that listed ZERO gates left no
    # diagnostic anywhere at all. Written only for non-PASS outcomes, so a green
    # sweep costs nothing.
    local logdir
    logdir="$(dirname "${out}")/logs"
    mkdir -p "${logdir}"

    load_long_arms

    local wanted
    wanted="$(classes_for_tier "${tier}")"
    preflight "${tier}"

    # Group the selected gates by cargo target so each test binary is invoked
    # once with an --exact filter per test, rather than once per test.
    local inv
    # Script-global for the same reason as SCRATCH above: a `local` here is
    # already out of scope when the EXIT trap runs, and `set -u` would make
    # the trap fail and mask the real exit status.
    SCRATCHDIR="$(mktemp -d)"
    trap 'rm -rf "${SCRATCHDIR:-}"' EXIT
    local tmpdir="${SCRATCHDIR}"
    # ONE inventory pass, reused below. inventory() is a full-tree scan
    # (~2.4 s over 1200 files); the old target_has_isolate() re-ran it once
    # per target inside the run loop — ~5 minutes of pure re-scanning across
    # 124 targets before any kernel launched.
    local full_inv="${tmpdir}/full-inv.tsv"
    inventory > "${full_inv}"
    inv="${tmpdir}/inv.tsv"
    awk -F'\t' -v want="${wanted}" '
        BEGIN { n = split(want, a, "\n"); for (i = 1; i <= n; i++) if (a[i] != "") keep[a[i]] = 1 }
        ($3 in keep) { print $1 "\t" $2 }
    ' "${full_inv}" > "${inv}"

    # Targets holding any `isolate`-class gate. Such a gate declares that a
    # faulting kernel poisons the CUDA context for everything sharing the
    # process, so it must not be batched with its siblings — and it DOES share
    # a target with 8 gpu-class gates. Computed from the FULL inventory, not
    # the tier-filtered one: the sibling gates run under --tier gpu even when
    # the isolate gate itself does not, and they still must not batch with it.
    declare -A ISOLATE_TARGET=()
    local isof
    while IFS= read -r isof; do
        [[ -z "${isof}" ]] && continue
        ISOLATE_TARGET["$(target_args "${isof}" | tr '\n' ' ')"]=1
    done < <(awk -F'\t' '$3 == "isolate" { print $1 }' "${full_inv}" | sort -u)

    local total
    total="$(wc -l < "${inv}")"
    echo "gpu-cert: tier=${tier} gates=${total}"
    if [[ "${total}" -eq 0 ]]; then
        echo "gpu-cert: nothing to run" >&2
        exit 2
    fi

    echo "gpu-cert: building test targets (--features ${CERT_FEATURES})"
    cargo test --workspace --features "${CERT_FEATURES}" --no-run --quiet

    : > "${out}"

    # Collapse source files onto cargo targets. Several src/ files share one
    # --lib target, so this both dedups invocations and unions their gates.
    local key
    while IFS=$'\t' read -r file fn; do
        [[ -z "${file}" ]] && continue
        key="$(target_args "${file}" | tr '\n' ' ')"
        printf '%s\t%s\n' "${key}" "${fn}" >> "${tmpdir}/bytarget.tsv"
    done < "${inv}"

    local targets
    targets="$(cut -f1 "${tmpdir}/bytarget.tsv" | sort -u)"

    # ALWAYS single-threaded. The GPU is one shared resource with one CUDA
    # context per process, and libtest's default is to run a target's tests
    # concurrently. The first full sweep ran them in parallel and reported 51
    # failures; re-running the same gates serially turned 4-of-4 CFIE decode
    # gates (and most of the rest) green. Concurrency was manufacturing
    # failures wholesale — a lane that cries wolf gets switched off, so this
    # is not a knob.
    #
    # One target at a time, too: concurrent `nsl` builds were what exhausted
    # /tmp during the lifetime campaign.
    local threads=(--test-threads=1)

    local args wanted_fns listed selected rc status nsel pkg feats
    while IFS= read -r key; do
        [[ -z "${key}" ]] && continue
        read -r -a args <<< "${key}"
        pkg="${args[1]}"
        feats="$(features_for_pkg "${pkg}")"
        local featarg=()
        [[ -n "${feats}" ]] && featarg=(--features "${feats}")

        # libtest, not the filename, is the authority on test NAMES: a gate
        # inside `mod tests` is `path::tests::name`, and --exact matches the
        # full path. Join cargo's listing to the classified basenames.
        mapfile -t wanted_fns < <(
            awk -F'\t' -v k="${key}" '$1 == k { print $2 }' "${tmpdir}/bytarget.tsv" | sort -u)
        mapfile -t listed < <(
            cargo test "${args[@]}" "${featarg[@]}" -- --ignored --list \
              < /dev/null 2> "${tmpdir}/list.err" \
            | sed -n 's/^\(.*\): test$/\1/p')
        mapfile -t selected < <(
            printf '%s\n' "${listed[@]}" | awk -v want="$(printf '%s\n' "${wanted_fns[@]}")" '
                BEGIN { n = split(want, a, "\n"); for (i = 1; i <= n; i++) if (a[i] != "") keep[a[i]] = 1 }
                { base = $0; sub(/^.*::/, "", base); if (base in keep) print $0 }')

        nsel="${#selected[@]}"

        # Account for EVERY wanted gate, not just the ones that matched. A
        # target can list some of its gates and not others — `wrga_b32_trigger_
        # measurement_requires_cuda` is #[cfg(not(feature = "cuda"))], so it
        # cannot exist in a CUDA build, while eight sibling gates in the same
        # target list fine. Marking NOTFOUND only when nsel==0 dropped that one
        # gate from the report with no trace: 255 selected, 254 reported. The
        # reconciliation check at the end catches the count, but the gate still
        # needs a row saying what happened to it.
        local miss matched
        matched=" $(printf '%s\n' "${selected[@]}" | sed 's/^.*:://' | tr '\n' ' ')"
        for miss in "${wanted_fns[@]}"; do
            case "${matched}" in
                *" ${miss} "*) ;;
                *) printf '%s\t%s\tNOTFOUND\t-\n' "${key}" "${miss}" >> "${out}" ;;
            esac
        done

        if [[ "${nsel}" -eq 0 ]]; then
            echo "  [${key}] 0 of ${#wanted_fns[@]} gate(s) listed — NOTFOUND"
            # A target listing nothing is usually a BUILD failure in the
            # `--ignored --list` step, not an absent gate — and that error text
            # was previously discarded, so the whole target arrived as silent
            # mass-NOTFOUND. Keep it.
            if [[ -s "${tmpdir}/list.err" ]]; then
                tail -c 200000 "${tmpdir}/list.err" > "${logdir}/$(slugify "${key}").list.err"
            fi
            continue
        fi

        local tmo
        tmo="$(timeout_for "${key}" "${timeout_s}")"
        if [[ "${tmo}" != "${timeout_s}" ]]; then
            echo "      timeout ${tmo}s (long-arm override; default ${timeout_s}s)"
        fi

        # A target holding an `isolate` gate skips batching entirely and goes
        # straight to one-process-per-gate, honouring that class's contract
        # instead of merely labelling it.
        if [[ -n "${ISOLATE_TARGET[${key}]:-}" ]]; then
            echo "  [${key}] ${nsel} gate(s) — isolate class: one process each"
            rc=1
            status=FAIL
        else
        # The batched run carries EVERY gate of this target, so its budget is
        # per-gate x count (clamped): a single per-gate number applied here
        # silently caps the whole target.
        local batch_to=$(( tmo * nsel ))
        if (( batch_to > batch_cap )); then batch_to="${batch_cap}"; fi
        echo "  [${key}] ${nsel} gate(s) (budget ${batch_to}s)"
        set +e
        t0=${SECONDS}
        timeout --signal=KILL "${batch_to}" \
            cargo test "${args[@]}" "${featarg[@]}" -- \
            --ignored --exact "${selected[@]}" "${threads[@]}" \
            < /dev/null > "${tmpdir}/out.txt" 2>&1
        rc=$?
        set -e

        case ${rc} in
            0)   status=PASS ;;
            137) status=TIMEOUT ;;
            *)   status=FAIL ;;
        esac
        fi

        if [[ "${status}" == "PASS" ]]; then
            local fn
            for fn in "${selected[@]}"; do
                # '~' = this is the TARGET's elapsed, shared by every gate in
                # the batched run (they execute concurrently inside one cargo
                # test). Only the per-gate rerun path below can attribute time
                # to a single gate.
                printf '%s\t%s\tPASS\t~%ss\n' "${key}" "${fn}" "$(( SECONDS - t0 ))" >> "${out}"
            done
            continue
        fi

        # CONFIRMATION PASS. A batch result cannot be trusted once anything in
        # the target failed: a kernel that faults poisons the CUDA context for
        # every LATER test in the same process, even at --test-threads=1. That
        # is not hypothetical — `a4_hd128_causal_true_rope_q_true_fused_proj_
        # true` was reported red purely because a1..a3 crashed ahead of it, and
        # it passes 3/3 alone. So when a target goes red, re-run each of its
        # gates in its OWN process and let that verdict stand.
        #
        # Only failing targets pay this cost, so a green sweep stays fast.
        # (An isolate-class target arrives here unconditionally — by design.)
        echo "      running ${nsel} gate(s) individually (one process each)"
        # The batch output is the only record of a failure that does NOT
        # reproduce in isolation (a gate poisoned by an earlier crash in the
        # same process). Keep it before the per-gate loop overwrites nothing —
        # `one.txt` is a different file, but the batch log was previously
        # discarded with the scratch dir either way.
        tail -c 200000 "${tmpdir}/out.txt" > "${logdir}/$(slugify "${key}").batch.log" 2>/dev/null || true
        local fn rc1 st1
        for fn in "${selected[@]}"; do
            set +e
            t1=${SECONDS}
            timeout --signal=KILL "${tmo}" \
                cargo test "${args[@]}" "${featarg[@]}" -- \
                --ignored --exact "${fn}" --test-threads=1 \
                < /dev/null > "${tmpdir}/one.txt" 2>&1
            rc1=$?
            set -e
            case ${rc1} in
                0)   st1=PASS ;;
                137) st1=TIMEOUT ;;
                *)   st1=FAIL ;;
            esac
            printf '%s\t%s\t%s\t%ss\n' "${key}" "${fn}" "${st1}" "$(( SECONDS - t1 ))" >> "${out}"
            if [[ "${st1}" != "PASS" ]]; then
                echo "      FAIL ${fn}"
                grep -E "^(thread .* panicked|assertion|error)" "${tmpdir}/one.txt" \
                    | head -3 | sed 's/^/           | /' || true
                tail -c 200000 "${tmpdir}/one.txt" \
                    > "${logdir}/$(slugify "${key}__${fn}").log" 2>/dev/null || true
            fi
        done
    done <<< "${targets}"

    echo ""
    # Bank the resolved configuration next to the report. Reading a 90-day-old
    # artifact otherwise leaves no way to tell whether a gate ran at 900s or
    # 1800s, or under which feature set — both of which change what a TIMEOUT
    # or NOTFOUND row means.
    {
        echo "tier	${tier}"
        echo "default_timeout_s	${timeout_s}"
        echo "features	${CERT_FEATURES}"
        local k
        for k in "${!LONG_ARM[@]}"; do
            echo "long_arm	${k}	${LONG_ARM[${k}]}"
        done
    } > "$(dirname "${out}")/run-metadata.tsv"

    echo "gpu-cert: report -> ${out}"
    echo "gpu-cert: per-gate logs -> ${logdir}"
    awk -F'\t' '{ c[$3]++ } END { for (k in c) printf "  %-8s %d\n", k, c[k] }' "${out}"

    # RECONCILE (review finding F6). Every selected gate must appear in the
    # report exactly once. Without this, any path that drops a target — a
    # future refactor, or a cargo invocation that consumed the loop's stdin —
    # leaves a SHORT report that still exits 0. A green lane that silently ran
    # fewer gates than it announced is the failure mode this whole file exists
    # to make impossible.
    local reported
    reported="$(wc -l < "${out}")"
    if [[ "${reported}" -ne "${total}" ]]; then
        echo "gpu-cert: INTERNAL — announced ${total} gate(s) but reported ${reported}." >&2
        echo "          The sweep is not trustworthy; refusing to report success." >&2
        exit 3
    fi

    # Regression posture: only gates NOT already known-red can fail the lane.
    local unexpected=0
    if [[ -s "${KNOWN_RED}" ]]; then
        # FILENAME==ARGV[1], not NR==FNR (review finding F8): if KNOWN_RED is
        # ever truncated to zero bytes, NR==FNR stays true for the report's
        # FIRST line, which would be eaten as an allowlist entry and never
        # checked.
        unexpected="$(awk -F'\t' -v kr="${KNOWN_RED}" '
            FILENAME == kr { if ($0 !~ /^#/ && $0 != "") red[$0]=1; next }
            $3 != "PASS" && !(($1 "\t" $2) in red) { n++ }
            END { print n + 0 }' "${KNOWN_RED}" "${out}")"
    else
        unexpected="$(awk -F'\t' '$3 != "PASS" { n++ } END { print n + 0 }' "${out}")"
    fi
    if [[ "${unexpected}" -gt 0 ]]; then
        echo "gpu-cert: ${unexpected} gate(s) red and not in ${KNOWN_RED}" >&2
        exit 1
    fi
    echo "gpu-cert: no unexpected failures"
}

usage() { sed -n '2,75p' "$0" | sed 's/^# \{0,1\}//'; }

# Bare invocation exits 2, not 0: a CI step that runs this with no argument
# must not read as a green check that did nothing. Explicit --help still exits 0.
if [[ $# -eq 0 ]]; then
    echo "gpu-cert: no command given" >&2; echo "" >&2; usage >&2; exit 2
fi

case "$1" in
    --list)            cmd_list ;;
    --write-manifest)  cmd_write_manifest ;;
    --check-inventory) cmd_check_inventory ;;
    --check-long-arms) cmd_check_long_arms ;;
    --run)
        shift
        if [[ "${1:-}" == "--tier" ]]; then
            [[ -n "${2:-}" ]] || { echo "gpu-cert: --tier needs a value" >&2; exit 2; }
            NSL_CERT_TIER="$2"; export NSL_CERT_TIER
            shift 2
        fi
        if [[ $# -gt 0 ]]; then
            # Refuse, don't drop: silently ignoring trailing arguments turned
            # a mistyped `--run --tier all --something` into a full run with
            # the option unapplied — an hour of hardware time answering a
            # question nobody asked.
            echo "gpu-cert: unknown argument(s) after --run: $*" >&2; exit 2
        fi
        # Self-wrap under the concurrency guard (scripts/gpu-guard.sh): flock
        # against other guarded runs, busy-device refusal against everything
        # else (an orphaned `nsl run` child holding 22 GB reads as a compute
        # bug otherwise), and the whole lane in its own process group so a
        # killed lane cannot orphan a child on the device. The tier selection
        # is already exported, so the re-exec needs no argument beyond --run.
        # `held` is the loop-break: it verifies the enclosing guard's
        # pid:starttime token, so a stale variable cannot skip the wrap.
        if [[ "${NSL_GPU_GUARD:-1}" != "0" ]] && ! "${ROOT}/scripts/gpu-guard.sh" held; then
            exec "${ROOT}/scripts/gpu-guard.sh" run -- "${ROOT}/scripts/gpu-cert.sh" --run
        fi
        cmd_run
        ;;
    -h|--help)         usage ;;
    # Anything else EXITS NON-ZERO. Printing help and exiting 0 (review finding
    # F5) meant a typo in a CI `run:` line — `--check-inventroy` — produced a
    # green job that checked nothing.
    *) echo "gpu-cert: unknown argument: $1" >&2; echo "" >&2; usage >&2; exit 2 ;;
esac
