#!/usr/bin/env python3
"""Render the corpus record from the artifacts themselves.

Every number here is read out of a manifest or off the disk at render time.
Nothing is transcribed by hand, and nothing is written from a run still in
flight -- a corpus that is missing prints as missing rather than as a remembered
figure.

Usage (from the repo root):
    tools/hfcorpus/.venv/bin/python tools/hfcorpus/report.py > \
        models/benchmarks/PRETRAIN_CORPUS_2026_08_19.md
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MIX = REPO / "data/tokens/mix"
TOKDIR = REPO / "models/tokenizers"


def manifests() -> list[dict]:
    out = []
    for mf in sorted(MIX.glob("*.manifest.json")):
        m = json.loads(mf.read_text())
        binp = REPO / m["output"]
        m["_exists"] = binp.exists()
        m["_bytes"] = binp.stat().st_size if binp.exists() else 0
        m["_name"] = binp.name
        out.append(m)
    return out


def main() -> int:
    print("# Pretraining corpus — Stack v3 + FineWeb + distillation + NSL sources\n")
    print("Generated by `tools/hfcorpus/report.py` from the corpus manifests; every")
    print("figure is read off disk at render time rather than transcribed.\n")

    print("## Sources\n")
    print("| set | dataset | taken |")
    print("|---|---|---|")
    print("| code | `HuggingFaceCode/stack-v3-train` | 20 of 8,192 shards, strided "
          "(full set is 3.54 TB / ~3.6T tokens) |")
    print("| web | `HuggingFaceFW/fineweb`, config `sample-10BT` | 14 of 15 parquet "
          "for train, the 15th held out whole |")
    print("| chat | `r0b0tlab/qwen3.8-max-glm5.2-kimi-k3-distillation`, `canonical` | "
          "52,205 train / 2,872 val / 2,860 test traces |")
    print("| nsl | `data/tokcorpus/combined_train.txt` | this repo + 15 unrelated "
          "local projects |\n")
    print("Stack shards are sampled with a **stride**, not a prefix: their "
          "partitioning\norder is undocumented and a prefix could correlate with "
          "repo size, language,\nor crawl order. The distillation set ships two "
          "overlapping shard series in one\ndirectory; the `-of-00006` series is "
          "the current export and a naive `train-*`\nglob would duplicate 41,682 "
          "traces.\n")
    print("## Corpora\n")
    print("| corpus | tokens | on disk | B/tok | source text |")
    print("|---|---:|---:|---:|---:|")
    # The mixture is BUILT FROM the others, so adding it to the same total would
    # count most tokens twice and report a corpus roughly twice its real size.
    unique = 0
    for m in manifests():
        if not m["_exists"]:
            print(f"| `{m['_name']}` | MISSING | — | — | — |")
            continue
        if "composition" not in m:
            unique += m["tokens"]
        bpt = m.get("bytes_per_token")
        src = f"{m['text_bytes'] / 1e9:.2f} GB" if "text_bytes" in m else "—"
        print(
            f"| `{m['_name']}` | {m['tokens']:,} | {m['_bytes'] / 1e9:.2f} GB | "
            f"{bpt if bpt is not None else '—'} | {src} |"
        )
    print(f"\n**{unique:,} unique tokens** across the source corpora. The mixture is")
    print("built from them and is listed above; it is deliberately excluded from that")
    print("sum, since counting both would double-count almost every token.\n")

    for m in manifests():
        if "composition" in m:
            print(f"### `{m['_name']}` composition\n")
            print("| part | tokens | share | epochs of that corpus |")
            print("|---|---:|---:|---:|")
            rep = m.get("repetition", {})
            for k, v in m["composition"].items():
                e = rep.get(k)
                print(f"| `{k}` | {v['tokens']:,} | {v['share']:.4%} | "
                      f"{e if e is not None else '1.000'} |")
            print(f"\nSeed `{m['seed']}`, end-of-document id `{m['eos_id']}`.\n")

    cmp_path = REPO / "data/tokenizer/comparison.json"
    if cmp_path.exists():
        print("## Tokenizer: v1 (code-trained) vs v2 (mix-trained)\n")
        print("Same two-stage spec — cl100k→line, `transition=40960`, vocab 49152,")
        print("`min_freq=2`. What differs is the training mixture and the reserved")
        print("special tokens (v1 reserved none). v2's sample tracks the corpus at")
        print("~58% code, so it recovers a pure-code tokenizer's compression on unseen")
        print("code while keeping a large gain on web. Bytes/token, higher is better.\n")
        print("| held-out set | v1 | v2 | change |")
        print("|---|---:|---:|---:|")
        labels = {"nsl": "this repo's held-out sources", "ood": "five unseen code projects",
                  "web": "FineWeb held-out shard", "sft": "distillation validation split"}
        for r in json.loads(cmp_path.read_text()):
            if r.get("v1") is None or r.get("v2") is None:
                continue
            d = (r["v2"] / r["v1"] - 1) * 100
            print(f"| {r['set']} — {labels.get(r['set'], '')} | {r['v1']:.3f} | "
                  f"{r['v2']:.3f} | {d:+.1f}% |")
        print()

    print("## Verification\n")
    print("`tools/hfcorpus/verify.py` checks token counts against manifests, that ids")
    print("fit the u16 stream, that the end-of-document id is present, and that the")
    print("web val set is neither the head nor a suffix of train. Beyond that, three")
    print("structural properties were measured directly:\n")
    print("* Documents survive tokenization: `stack_train.bin` carries 424,728")
    print("  `<|endoftext|>` ids against 424,728 extracted documents, and 5,282,296")
    print("  `<|file_sep|>` markers — 12.4 files per repository.")
    print("* Chat structure survives: every `<|im_start|>` in the rendered text maps")
    print("  to exactly one id (212,849 of each), and the tool-call counts reproduce")
    print("  the dataset card's own mixture table (5,952 / 10.27%).")
    print("* The mixture is interleaved, not blocked: `<|file_sep|>` density across")
    print("  ten deciles of `pretrain_train.bin` is 388-419 per million tokens, a")
    print("  1.08x spread. A run consuming any prefix gets the intended proportions.\n")
    print("* `decode(encode(x))` is exact on all held-out sets: 20,000/20,000 web,")
    print("  2,872/2,872 chat, 158/158 code.\n")
    sp = TOKDIR / "special_tokens.json"
    if sp.exists():
        rec = json.loads(sp.read_text())
        print("## Reserved ids\n")
        print("Not contiguous: surfaces the chat sample taught BPE as ordinary merges")
        print("keep the id they were learned at, and `add_special_tokens` reuses it.\n")
        print("| surface | id |")
        print("|---|---:|")
        for k, v in rec["ids"].items():
            print(f"| `{k}` | {v} |")
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
